### ISSUE TITLE
Player State Error not captured with VLC 3.0.0

### ISSUE THREAD

**Issue by Neraste** [oaubert/python-vlc#10]
I am experimenting the (beta) 3.0.0 version of VLC with this (cool) Python wrapper.

When an error occurs (eg: file not found, file empty), player.get_state() (with player = vlc.Instance().media_player_new()) is never equal to vlc.State.Error, but to vlc.State.Ended instead.

Maybe the error is on vlc 3.0.0's side, but...

**Comment by oaubert** [comment]
This behaviour does not happen on vlc 2.2.1 (it correctly reports vlc.State.Error), so it is definitely a libvlc issue. You should report it on vlc-devel.
