### ISSUE TITLE
Subtitle (add slave) not working on Windows

### ISSUE THREAD

**Issue by atvKumar** [oaubert/python-vlc#100]
I would like to raise the issue of add slave (external subtitle, file) example srt file. Requires a physical file to be located in the same location with a same name. Before it is loaded.
The app also needs to be restarted in order for it to take effect.

Any other filename, or location is not working with the add_slave method.
A dynamically updated srt file (subtitle software) also is not shown, and requires a restart.

On the mac osx its working fine. I only face the issue with i port over to windows.
Please do help.

**Comment by mrJean1** [comment]
Make sure to include a URI scheme to specify the slave file, like `"file://..."`, see the `MediaPlayer.add-slave.__doc__` description.

If that still doesn't work, the issue is inside the VLC library.  Perhaps, report the problem on the [VLC forum](https://forum.videolan.org).

**Comment by atvKumar** [comment]
Yes I have added the file:// and still the issue exists. I will post on the vlc forums.

**Comment by oaubert** [comment]
Thanks for closing this bug. @atvKumar If you found a solution, it would be nice to post it/its links here, so that the next person who has the same issue does not hit a dead end here.
