### ISSUE TITLE
Setting VLC volume is same as setting system volume?

### ISSUE THREAD

**Issue by flatsiedatsie** [oaubert/python-vlc#101]
On my pc, setting the volume of VLC is different from setting the system volume. They are relative to each other.

It seems that with Python VLC this distinction is not made? When I use the `.audio_set_volume(volume)` on a Raspberry Pi from the console, it's akin to changing the master volume.

I suspect this 'works as intended'. I just wanted to make sure.

**Comment by oaubert** [comment]
The libvlc_media_player_audio_set_volume implementation is dependent on the audio output module. It may happen that the raspberry Pi audio output module behaves differently from the PC one. This is not dependent on the python bindings, so you should rather ask this question on forum.videolan.org
