### ISSUE TITLE
player.video_set_adjust_int(vlc.VideoAdjustOption.Enable, 1) throws errors

### ISSUE THREAD

**Issue by Jow2meeM** [oaubert/python-vlc#102]
I'd like to change the brightness but when I try to enable VideoAdjustOption I get lots of these errors:

```
[0084f9a8] chain filter error: Too high level of recursion (3)
[0084f438] main filter error: Failed to create video converter
...
[6df02cd0] main video output error: Failed to create video converter
[6df02cd0] main video output error: Failed to compensate for the format changes, removing all filters
```

As a result VideoAdjustOption isn't enabled since player.video_get_adjust_int(vlc.VideoAdjustOption.Enable) returns 0.

Thank you for sharing your ideas, insights, tips regarding the matter!

Example code:
```
import vlc, time
player = vlc.MediaPlayer('video.mp4')
player.play()
time.sleep(10)
player.video_set_adjust_int(vlc.VideoAdjustOption.Enable, 1) #throws errors
time.sleep(10)
print(player.video_get`_adjust_int(vlc.VideoAdjustOption.Enable)) #returns 0

player.video_set_adjust_float(vlc.VideoAdjustOption.Brightness, 0.0)
player.video_get_adjust_float(vlc.VideoAdjustOption.Brightness) #returns 0.0
```

python-vlc 3.0.7110
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
Raspberry 3B+ (Raspian Buster)
Linux 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

**Comment by mrJean1** [comment]
Adjusting the `vlc.VideoAdjustOption.Brightness` requires using the `player.video_set_adjust_float(vlc.VideoAdjustOption.Brightness, value)` method with a `value` between 1.0 and 2.0.  Similarly for other adjustments `.Contrast`, `.Gamma`, `.Hue` and `.Saturation`.

Only use the `player.video_set_adjust_int` method to en- or disable video adjustments, as in `player.video_set_adjust_int(vlc.VideoAdjustOption.Enable, 1)`.  More details [here](http://Wiki.VideoLan.org/Documentation:Modules/adjust).

**Comment by Jow2meeM** [comment]
Unfortunately neither the change of the enabled flag nor the change in brightness is applied because `player.video_set_adjust_int(vlc.VideoAdjustOption.Enable, 1)` throws the aforementioned errors, resulting in `player.video_get_adjust_int(vlc.VideoAdjustOption.Enable)` to return 0.

`player.video_set_adjust_float(vlc.VideoAdjustOption.Brightness, 0.0)` changes the value accordingly, as the return value of `player.video_get_adjust_float(vlc.VideoAdjustOption.Brightness)` suggests (in this example 0.0).
