### ISSUE TITLE
MEdiaPlayer works in one file, doesn't work in another

### ISSUE THREAD

**Issue by sedthh** [oaubert/python-vlc#104]
Playing a song from mp3.py's __main__ works, however if I import mp3.py I get this error message: 

 File "mp3.py", line 10, in __init__
    self.audio = MediaPlayer(file)
  File "C:\Python3\lib\site-packages\vlc.py", line 3310, in __new__
    o = instance.media_player_new()
AttributeError: 'NoneType' object has no attribute 'media_player_new'

I'm on 64-bit Windows, Python 3.7 with the most recent VLC installed.

**Comment by mrJean1** [comment]
What are the versions of your vlc.py and VLC?  Try import vlc; print(vlc.__version__, vlc.libvlc_get_version())

**Comment by sedthh** [comment]
I've realized what caused the problem: 
I had the libvlc.dll and libvlccore.dll files next to the python script, which for some reason caused the vlc library to find and use them, causing the instance creation to fail.

Removing these dlls have solved the issue.
