### ISSUE TITLE
MediaListPlayer window interruption when playing next file

### ISSUE THREAD

**Issue by Jow2meeM** [oaubert/python-vlc#106]
Before playing the next file in the media list the player closes and reopens its window. Is there a way to prevent this behavior and instead have a seamless transition to the next video?

Example code:
```
#!/usr/bin/env python3
import time, vlc

instance = vlc.Instance()
media_list = instance.media_list_new(['./video_01.mp4', './video_02.mp4'])
list_player = instance.media_list_player_new()
list_player.set_media_list(media_list)

list_player.play()
time.sleep(5)
list_player.next()

while True:
    time.sleep(300)
```

This happens also when the playback is repeated (or looped).

```
#!/usr/bin/env python3
import time, vlc

instance = vlc.Instance()
media_list = instance.media_list_new(['./video_01.mp4', './video_02.mp4'])
list_player = instance.media_list_player_new()
list_player.set_media_list(media_list)

list_player.play()
list_player.set_playback_mode(vlc.PlaybackMode.repeat)

while True:
    time.sleep(300)
```
Raspberry Pi 3 Model B Plus Rev 1.3
Raspbian GNU/Linux 10 (buster)
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)

**Comment by Jow2meeM** [comment]
I'm positive now that this isn't a python-vlc issue. The same behavior shows when using C++/libvlc. The programs also run just fine on Ubuntu, without collapsing the player window in-between MediaList items.

**Comment by oaubert** [comment]
Thanks for the reports and the following investigation. Since this bug tracker is dedicated to python-vlc, the best way to proceed would be to report it on trac.videolan.org, referencing your RPi bug report with the C version.

**Comment by Jow2meeM** [comment]
[https://trac.videolan.org/vlc/ticket/22811](https://trac.videolan.org/vlc/ticket/22811)
