### ISSUE TITLE
ppp_services in vlc.Instance.renderer_discoverer_list_get(self, ppp_services)

### ISSUE THREAD

**Issue by Jow2meeM** [oaubert/python-vlc#109]
I'd like to use vlc.MediaPlayer.set_renderer(self, p_item) [1]. After sort of a wild goose chase through the documentation, I got stuck on how to create ppp_services [2]. It would be super nice if you could elaborate on this. The question also came up on the VideoLAN forum [3].

Generally it would be extremely helpful to have an verbose example on how to set the renderer, given the complexity of this process and the somewhat confusing documentation.

[1] http://olivieraubert.net/vlc/python-ctypes/doc/vlc.MediaPlayer-class.html#set_renderer
[2] http://olivieraubert.net/vlc/python-ctypes/doc/vlc.Instance-class.html#renderer_discoverer_list_get
[3] https://forum.videolan.org/viewtopic.php?f=32&t=146054&p=479125&hilit=libvlc_renderer_discoverer#p479034

**Comment by AlmBMouth** [comment]
+1 on this. 

I've been going through the documentation for a while now, but I can't seem to figure it out. An example on how to get this to work would be greatly appreciated.

**Comment by mrmutator** [comment]
I'm stuck at the same problem and would be grateful for an example.

**Comment by mrmutator** [comment]
OK. I figured it out if anyone is interested.
I'm using `mdns_renderer` as the discoverer service. I had a look at the [services_discovery](https://github.com/videolan/vlc/tree/master/modules/services_discovery) module in the VLC code. Maybe some other services work as well?!

Here's an example about how to put everything together. It works on my Chromecast 3.
```python
import vlc
import time


i = vlc.Instance()
media_player = i.media_player_new()

renderers = []
def onEvent(event):
    r = vlc.Renderer(event.u.media).hold()
    renderers.append(r)


discoverer = i.renderer_discoverer_new("mdns_renderer")
event_manager = discoverer.event_manager()
event_manager.event_attach(vlc.EventType.RendererDiscovererItemAdded, onEvent)
discoverer.start()
time.sleep(5)
discoverer.stop()
discoverer.release()
media_player.set_renderer(renderers[0])

media_player.set_mrl("my/video/file")
media_player.play()

i.wait()
```

**Comment by Gzsiceberg** [comment]
I spent a lot time to debug it. I think it's a bug. The function `libvlc_media_discoverer_list_get` args should be `ctypes.POINTER(ctypes.POINTER(ctypes.POINTER(MediaDiscovererDescription))` instead of `ctypes.POINTER(ctypes.POINTER(MediaDiscovererDescription)`

Here's the example works.
```
import vlc
import ctypes
ins = vlc.Instance()
p_mdd = ctypes.POINTER(vlc.MediaDiscovererDescription)()
cnt = ins.media_discoverer_list_get(1, ctypes.byref(p_mdd))
print(cnt)
print("-" * 80)

pp_mdd = ctypes.cast(p_mdd, ctypes.POINTER(ctypes.POINTER(vlc.MediaDiscovererDescription)))
print(pp_mdd[0].contents.name)
```

**Comment by Gzsiceberg** [comment]
I think there's a bug in python interface. The ppp_services need be `ctypes.POINTER(ctypes.POINTER(ctypes.POINTER(RDDescription)) ` instend of `ctypes.POINTER(ctypes.POINTER(RDDescription)`.

Here's a example works.
```
import vlc
import ctypes
ins = vlc.Instance()

print("media")
p_mdd = ctypes.POINTER(vlc.MediaDiscovererDescription)()
cnt = ins.media_discoverer_list_get(1, ctypes.byref(p_mdd))
print(cnt)
print("-" * 80)

pp_mdd = ctypes.cast(p_mdd, ctypes.POINTER(ctypes.POINTER(vlc.MediaDiscovererDescription)))
print(pp_mdd[0].contents.name, pp_mdd[0].contents.longname, pp_mdd[0].contents.cat)


print("render")
p_mdd = ctypes.POINTER(vlc.RDDescription)()
cnt = ins.renderer_discoverer_list_get(ctypes.byref(p_mdd))
print(cnt)
print("-" * 80)

pp_mdd = ctypes.cast(p_mdd, ctypes.POINTER(ctypes.POINTER(vlc.RDDescription)))
print(pp_mdd[0].contents)
```

**Comment by oaubert** [comment]
Hi. Thanks for the investigation and fix. I have integrated it in the git tree, you can test it. If you feel like it, since you have invested time in this issue, you could provide a test case to add to the test suite, and/or an example code that I could integrate in the examples directory.
