### ISSUE TITLE
It seems it only works with 32-bit VLC, not with the 64-bit version

### ISSUE THREAD

**Issue by ric2b** [oaubert/python-vlc#11]

**Comment by oaubert** [comment]
It definitely works with the 64-bit vlc at least on my OS (linux), and I had reports that it also works on windows and macosx. It would help if you are more precise in the description of the problem. The minimum you should provide is your precise OS/architecture information and the error messages or a description of the exact symptoms.

**Comment by ric2b** [comment]
Running it on 64bit Windows 8.1 with a 64bit installation of VLC 2.2.1 yields the following error:
```python
File "...", line 44, in play_audio_file
    import vlc
  File "C:\Python34\lib\site-packages\vlc.py", line 173, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Python34\lib\site-packages\vlc.py", line 146, in find_lib
    dll = ctypes.CDLL('libvlc.dll')
  File "C:\Python34\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```
The error occurs as soon as I try to import it. 
(Python version is 3.4.2 and python-vlc is at 1.1.2 in this traceback)
It also happens on another computer I have that is running 64bit Windows 10 and 64bit VLC.

I have no issues when running on a computer that has a 32bit version of VLC, although that computer is running Linux Mint 17. I assume from the error message that the OS itself insn't relevant but if you think it would help I can try installing a 32bit VLC on one of my Windows PC's.
Thanks for the quick response!

**Comment by oaubert** [comment]
There is an architecture (32vs64) mismatch between your python version and you vlc version. Use
`python -c 'import ctypes; print 8 * ctypes.sizeof(ctypes.c_voidp)'` to know the architecture your python is compiled for. If you get 64, double-check that you VLC install is indeed for 64bits archs.

**Comment by ric2b** [comment]
Oh, didn't know they had to match, thanks!

**Comment by tengerdata** [comment]
Thanks for this info.

I used: **pip install python-vlc** in my Conda environment and I probably have the same issue 32bit vs 64bit, do you know how I to install the 64bit python-vlc version on Conda using pip install?

**Comment by oaubert** [comment]
As said above, you need to check that your python interpreter and VLC install are both compiled for the same architecture. The python-vlc module is pure python, so as long as python and VLC are compatible, it will work.

**Comment by tengerdata** [comment]
Thanks for your reply. So, now instead of installing python-vlc, I just downloaded the vlc.py file and placed it in a folder. When I open vlc.py with the python 2.7 interpreter it works and when I open it with the python 3.4 interpreter it won't work.

The architecture is different for python 3.4 and python 2.7, so vlc.py will only work with python 2.7. Do you have any suggestion on how to solve this problem? I can't use vlc.py with python 2.7 for my project because all my other libraries are in python 3.4.

**Comment by oaubert** [comment]
You have to install compatible (arch-wise) version of Python and VLC. Once it is done, the vlc.py module will work correctly. So given your information, you should probably change your python 3.4 install.

If you still have issues, please report accurate OS/version information, by sending the output of the following commands in both python2 and python3:

import platform
platform.architecture()
platform.uname()
platform.python_version()

**Comment by tengerdata** [comment]
Thanks for your help. 

I am using anaconda for all my packages, including Python 3. But, my conda root is 64bits so even if I create a new environment in conda and install Python 2, the root will still be 64bit. I tried this and VLC won't work.

For some reason VLC will only work when the platform architecture is 32bit. There must be a way to solve this problem somehow but I just can't wrap my head around this issue.

And, yes, you're right, when the Python version and VLC is compatible, i.e. 32bit Python architecture, it works fine. But, I can't create this architecture in my 64bit conda.
