### ISSUE TITLE
Cannot find the Picture class in the generated code

### ISSUE THREAD

**Issue by phill-85** [oaubert/python-vlc#112]
Its documented here, but I cannot find it in the code. Ran make no change. Kubuntu 19.04

Is there a better way to discuss dev issuse?

**Comment by mrJean1** [comment]
Which Picture class are you looking for?  Snapshot?

**Comment by phill-85** [comment]
Sorry, forgot the documentation link https://www.olivieraubert.net/vlc/python-ctypes/doc/vlc.Picture-class.html

**Comment by mrJean1** [comment]
The Picture documentation is extracted from VLC `4.0-dev-...`, see the very top.  There is no generated `vlc.py` Python-VLC file.

**Comment by oaubert** [comment]
My bad, the online documentation was generated from bindings corresponding to the development (git tree) vlc version. I have changed it to come from the latest release branch.
