### ISSUE TITLE
Report the bug for " FileNotFoundError: Could not find module 'libvlc.dll' "

### ISSUE THREAD

**Issue by liekong** [oaubert/python-vlc#118]
I found a bug by using the python-vlc on the windows7 & python3.8
It always show the error message like
“FileNotFoundError: Could not find module 'libvlc.dll'. Try using the full path with constructor syntax.”
I solve it to modify the line 163 of “vlc.py”，
from ”dll = ctypes.CDLL(libname)“ to ”dll = ctypes.CDLL('./'+libname)“.
It works.
Did it a problem in particular environment?

**Comment by RaviFefar** [comment]
To add cwd to search path:

```
import os
os.add_dll_directory(os.getcwd())
```

Instead of the current directory, add the directory where the VLC player is installed.

```
import os
os.add_dll_directory(r'C:\Program Files\VideoLAN\VLC')

import vlc
```

I download VLC 3.* in case my version of python-vlc is 3.*, then I copy plugins,**libvlc.dll** and **libvlccore.dll** to **C:\Windows\System64**.

**Comment by K4bl0-Skat3R** [comment]
also you can add path variable 
open cmd:
type: set PATH="%PATH%;C:\Program Files\VideoLAN\VLC\"
