### ISSUE TITLE
Problem with rtsp with python-vlc

### ISSUE THREAD

**Issue by vipien** [oaubert/python-vlc#12]
Hello @oaubert , I am writing because I have a rather strange problem with vlc.py. I'm connecting with his example "qtvlc.py" to a RTSP cameras. The strange thing is that there are 2 cameras connected to the same DVR and can not see one. The other I can see no problems. If you like and can test yourself directions are:

rtsp://75.149.45.50:554/cam/realmonitor?channel=1&subtype=0&unicast=true&authbasic=YWRtaW46YWRtaW4=

rtsp://75.149.45.50:554/cam/realmonitor?channel=3&subtype=0&unicast=true&authbasic=YWRtaW46YWRtaW4=

​The first is that I can not see and the error is :

"[03215fc4] live555 demux error: Nothing to play for rtsp: //75.149.45.50: 554 / cam / realmonitor channel = 1 & subtype = 0 Unicast = true auth basic = YWRtaW46YWRtaW4 = proto = Onvif "​

But if I can connect to the same camera with vlc media player without problem.

Thank you so much, hope you can help me.

**Comment by vipien** [comment]
The problem was the timer that left no time to play that camera.

**Comment by heltucosta** [comment]
Could you elaborate a little more? I'm having a similar problem and didn't quite understood what you meant.
