### ISSUE TITLE
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647

### ISSUE THREAD

**Issue by hj1933** [oaubert/python-vlc#122]
I use the set_position () method to set the video progress bar. The video of the rtmp source is played, but the value obtained by get_position () is 3.4028234663852886e + 38, which causes the following error to occur when setting the progress:

```python
Traceback (most recent call last):
  File "D:/pycharm resource/Projects/gui/????/????/05. ??????????.py", line 129, in update_ui
    self.positionslider.setValue(media_pos)
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
```

**Comment by albusSimba** [comment]
I think the function only supports integers because that's the max and min of integers

**Comment by oaubert** [comment]
`MediaPlayer.get_position()` returns a float between 0.0 and 1.0. I do not have any rtmp test URL to properly test, but anyway, you can check if it returns a value outside of the valid range before trying to use the value to update  your UI.
