### ISSUE TITLE
Resize to eliminate overscan

### ISSUE THREAD

**Issue by TyrelCB** [oaubert/python-vlc#123]
I have a 4k TV however I'm only able to provide a 1080p source, when I do there is an overscan, I fix this at the OS level (Rasbian) with this setting in the boot config.
 ```
overscan_left=32
overscan_right=32
overscan_top=18
overscan_bottom=18
```
However when I start up a vlc.MediaPlayer instance and toggle_fullsceen() the video is larger than the screen. It seems to disregard the overscan settings above. 

Is there a way to manually resize the video to a resolution of say (1856x1048)?

**Comment by oaubert** [comment]
This is not specific to the python bindings, this question would have more chance of being answered on https://forum.videolan.org/
