### ISSUE TITLE
vlc.MediaListPlayer.get_media_player() not implemented?

### ISSUE THREAD

**Issue by lethargilistic** [oaubert/python-vlc#13]
This method is [documented](https://www.olivieraubert.net/vlc/python-ctypes/doc/vlc.MediaListPlayer-class.html#get_media_player) and [included in vlc.py](https://github.com/oaubert/python-vlc/blob/master/generated/vlc.py#L2678), but the binding is broken.

```python3
>>> import vlc
>>> mlp = vlc.MediaListPlayer()
>>> mp = mlp.get_media_player()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lethargilistic/Dev/player/vlc.py", line 2681, in get_media_player
    return libvlc_media_list_player_get_media_player(self)
  File "/home/lethargilistic/Dev/player/vlc.py", line 5052, in libvlc_media_list_player_get_media_player
    ctypes.c_void_p, MediaListPlayer)
  File "/home/lethargilistic/Dev/player/vlc.py", line 249, in _Cfunction
    raise NameError('no function %r' % (name,))
NameError: no function 'libvlc_media_list_player_get_media_player'
```

Clearly, the problem is that `libvlc_media_list_player_get_media_player` doesn't seem to exist. Has that not been implemented? Was it implemented and then its name changed?

**Comment by lethargilistic** [comment]
Python 3.5.1+, by the way. Doubt it would matter, but still.

**Comment by oaubert** [comment]
The python version does not really matters, please indicate rather your OS and vlc version.
The `libvlc_media_list_player_get_media_player` function has been implemented recently and is not  yet in a released version of VLC. The python bindings are generated from the VLC development include files, so they wrap some functions that may not yet be available.
If you really need this method, you should upgrade libvlc to a nightly snapshot for instance.

**Comment by thedangler** [comment]
I dowloaded the newest windows version of vlc and tried using get_media_player()
and I still get the libvlc_media_list_player_get_media_player no function error.
how exactly do I update libvlc only or regenerate the bindings?

**Comment by oaubert** [comment]
What is the output of the following python commands ?
`import vlc
print vlc.libvlc_get_version()`

**Comment by thedangler** [comment]
'2.2.4 Weatherwax'
which is odd because i downloaded am running 3.0.0-git Vetinari  
I looked in the about vlc tab.
I installed the new one over the old one

**Comment by thedangler** [comment]
Well, now I can't import vlc after updating to 3.0.0 
WindowsError: [Error 193] %1 is not a valid Win32 application
is the error I get now after doing import vlc

**Comment by devxpy** [comment]
I have the same issue, 

```
>>> vlc.libvlc_get_version()
b'2.2.6 Umbrella'
```

**Comment by oaubert** [comment]
You should update to vlc 3.0 which is the new stable version.
