### ISSUE TITLE
video output creation failed - fresh Debian install

### ISSUE THREAD

**Issue by 1day2die** [oaubert/python-vlc#139]
Hey Guys,

i tried a simple 6-liner

`		Instance = vlc.Instance()`
		`player = Instance.media_player_new()`
		`player.set_hwnd(my_label.winfo_id())   #tkinter label or frame`
		`media = Instance.media_new(video_name)`
		`player.set_media(media)`
		`player.play()`

where i use python-vlc to play a video (video_name) on a tkinter label (my_label)

When doing so on my windows machine, it runs perfectly.
When i run it on a fresh debian install (obviously with all needed packages and VLC installed) the console throws some errors and no video is played

`main Video output error: video output creation failed`
`main decoder error: failed to create video output`
`get_buffer() failed`
`thread_get_buffer() failed`
`decode_slice_header error`
`no frame!`

Anyone else experienced this on Debian? I saw someone having the same troubles on MacOS here

**Comment by mrJean1** [comment]
Assuming you're using `tkvlc.py` on Debian, type these commands in a terminal window:

```
python tkvlc.py -v
python vlc.py -v
```

**Comment by oaubert** [comment]
I am also using Debian, and the tkvlc example works for me, apart from the menubar window, which is frozen, but the app + play/pause from the File menu work, with video embedded.

**Comment by 1day2die** [comment]
> Assuming you're using `tkvlc.py` on Debian, type these commands in a terminal window:
> 
> ```
> python tkvlc.py -v
> python vlc.py -v
> ```
tkvlc is 20.05.04  (tkinter 8.6)

**Comment by 1day2die** [comment]
> I am also using Debian, and the tkvlc example works for me, apart from the menubar window, which is frozen, but the app + play/pause from the File menu work, with video embedded.

i just tried that. working fine. seems to be a issue with my code then which is weird cause theres not a lot of code..lol thanks!
