### ISSUE TITLE
Error When Importing VLC

### ISSUE THREAD

**Issue by kethan1** [oaubert/python-vlc#140]
I am using 64-bit python 3.8.3. I have install vlc using `pip install python-vlc`. I am getting the following error:

`
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import vlc
  File "C:\Users\--\AppData\Local\Programs\Python\Python38\lib\site-packages\vlc.py", line 210, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Users\--\AppData\Local\Programs\Python\Python38\lib\site-packages\vlc.py", line 170, in find_lib
    dll = ctypes.CDLL('.\\' + libname)
  File "C:\Users\--\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 
'C:\Users\--\AppData\Local\Programs\Python\Python38\libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax.
`

Edit: I am using Windows, and I have installed VLC before installing the python module.

**Comment by oaubert** [comment]
@pjeanjean  do you have an idea? Since this occurs on windows (that I do not use) and seems to be impacted by your patch.

**Comment by pjeanjean** [comment]
From the message, I am guessing that VLC is not installed on the computer (or at least that the install path was not found from the registry), and python-vlc resorted to try and get the dll from the working directory.
Now, for some reason, the working directory as seen by the Python Interpreter is `C:\Users\--\AppData\Local\Programs\Python\Python38\`, and I'm honestly not sure why, might be my bad because of a missing `chdir` but I do remember testing this and concluding that was not necessary.

I would like to look a bit more into it, but I don't have my Windows computer with me at the moment.

In the meantime:
> I have install vlc using `pip install python-vlc`

Please note that this command will not install VLC, but only this Python library, and you need to install VLC independently.

**Comment by kethan1** [comment]
Yes, I have installed vlc separately before I install the vlc python module. I am running windows 10.

**Comment by kethan1** [comment]
Sorry, accidently closed issue.

**Comment by pjeanjean** [comment]
Can you check your registry?
The library is supposed to get the registry key `HKEY_LOCAL_MACHINE/Software/VideoLAN/VLC/InstallDir` and use it to find `libvlc.dll`.
If this fails, it should look directly for "Program Files/VideoLan/VLC/libvlc.dll".

In your case, the registry key is not found, and the direct lookup also fails (where is VLC installed, and can you see the dll in the directory?)

**Comment by kethan1** [comment]
Hi, for me, it is located in "C:\Program Files (x86)\VideoLAN\VLC\libvlc.dll".

**Comment by pjeanjean** [comment]
Well, as a temporary workaround you could put the dll inside `C:\Users\--\AppData\Local\Programs\Python\Python38` if you want to use the library anyway.

Last question (for now): did you install VLC through the official installer, or did you use some kind of package manager (Microsoft Store, choco, ...)?

I will try to reproduce this issue when I have access to my Windows computer.

**Comment by kethan1** [comment]
I have used the official installer. It is not urgent, so I will wait for a bug fix.

**Comment by kethan1** [comment]
Any update on this? The error still happens. Do I need to upgrade python to Python 3.8.5 instead of Python 3.8.3.?

**Comment by pjeanjean** [comment]
Sorry, I forgot all bout this but I'll make a PR this evening to fix it.
Updating your Python version shouldn't change anything, we just need to add `Program Files (x86)` to the list of directories where VLC might be installed.

**Comment by kethan1** [comment]
Oh, okay, thank you so much.

**Comment by pjeanjean** [comment]
Just to be sure, could you try with this commit?
https://github.com/pjeanjean/python-vlc/commit/bf63e879ce83224302349229fddfc3f11d1cf955

**Comment by kethan1** [comment]
I just have to download the master zip, unzip it, and run `python setup.py` in the terminal right?

**Comment by kethan1** [comment]
I tried running setup.py and I got this error: 
```
C:\Users\ketha\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
C:\Users\ketha\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py:472: UserWarning: The version specified ('%s"') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

Sorry, if this is very basic stuff, I am new to this git thing.

**Comment by kethan1** [comment]
I tried doing python setup.py install and I got this:

```
C:\Users\ketha\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
C:\Users\ketha\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py:472: UserWarning: The version specified ('%s"') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running install
running bdist_egg
running egg_info
creating python_vlc_generator.egg-info
writing python_vlc_generator.egg-info\PKG-INFO
writing dependency_links to python_vlc_generator.egg-info\dependency_links.txt
writing top-level names to python_vlc_generator.egg-info\top_level.txt
writing manifest file 'python_vlc_generator.egg-info\SOURCES.txt'
error: package directory 'generator/generate' does not exist
```

**Comment by pjeanjean** [comment]
Close, run setup.py from `generated/3.0` ;)

**Comment by kethan1** [comment]
The first time I import it, I get this error:

```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import vlc
  File "C:\Users\ketha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_vlc-3.0.11114-py3.8.egg\vlc.py", line 223, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Users\ketha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_vlc-3.0.11114-py3.8.egg\vlc.py", line 172, in find_lib
    dll = ctypes.CDLL('.\\' + libname)
  File "C:\Users\ketha\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

The second time I import it, it gives me this error:
```
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import vlc
  File "C:\Users\ketha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_vlc-3.0.11114-py3.8.egg\vlc.py", line 223, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Users\ketha\AppData\Local\Programs\Python\Python38\lib\site-packages\python_vlc-3.0.11114-py3.8.egg\vlc.py", line 186, in find_lib
    dll = ctypes.CDLL(p)
  File "C:\Users\ketha\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by pjeanjean** [comment]
Weird, this time it actually found the dll but couldn't load it.
Are you using a 32bit version of Python by any chance?

**Comment by kethan1** [comment]
No, I am using python 64bit.

**Comment by pjeanjean** [comment]
Oh, so maybe the issue is that your version of vlc is 32bits while your Python is 64 (which would also explain why it is installed in `Program Files (x86)`)

**Comment by kethan1** [comment]
Is there a 64bit version of vlc?

**Comment by pjeanjean** [comment]
Well, mine is:

> libvlc.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows

And the website has both options for download

**Comment by kethan1** [comment]
Okay, thanks.

**Comment by kethan1** [comment]
Okay, Thanks!
