### ISSUE TITLE
how to get a track bar of video using vlc module

### ISSUE THREAD

**Issue by hacker6914** [oaubert/python-vlc#147]
sir,
i want to implement video position track-bar in my project using scale widget tkinter.
how can i get trackbar for my video player.
Thank u!!!

**Comment by mrJean1** [comment]
Take a look at the `.timeSlider` of the `Player` class in `examples/tkvlc.py`.

**Comment by hacker6914** [comment]
> examples/tkvlc.py

thank u!!! My issue is now solved......
