### ISSUE TITLE
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection terminated

### ISSUE THREAD

**Issue by shashfrankenstien** [oaubert/python-vlc#154]
```
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection terminated
```

This error occasionally occurs and interrupts audio playback. I'm unable to find the cause. It might be related to how ALSA and Pulse are configured on my machine. 

However, I'm raising this issue in the Python package repository, as I'm looking for a way to catch the error and attempt to retry. I've tried registering events, but failed to catch this error. Is this possible to do from Python?

OS: Pop!_OS 20.04
Python 3.8.2
VLC version: 3.0.9113

**Comment by oaubert** [comment]
AFAIK, there is no way to deal with this kind of error either at python level or libvlc level. The logical solution would be to add some API for handling (if it is possible) at the libvlc level, which would then be wrapped by language bindings.

**Comment by shashfrankenstien** [comment]
I was able to get around this by forcing VLC to pick alsa when creating an instance.
`vlc.Instance("--aout alsa")`

**Comment by oaubert** [comment]
Thanks for the feedback, it will be useful for other users facing the same issue.
