### ISSUE TITLE
Vlc won't work with frameless and translucent window in Pyqt5

### ISSUE THREAD

**Issue by hacker6914** [oaubert/python-vlc#155]
I have posted the question deatails in https://stackoverflow.com/questions/64725900/vlc-wont-work-with-framelesswindow-and-transparent-translucent-background-in-py
Please Check.

**Comment by mrJean1** [comment]
FWIW, this is not PyQt5 and now Windows, but `VLC/python-vlc` _does work_ in a transparent window on macOS (using the `cocoavlc.py` example and the latest [PyCocoa](https://pypi.org/project/PyCocoa/) release), meaning ... the video _is_ playing just the same way as in an opaque window.

What different or other behavior to expect after setting a window to _transparent_ and then show video or other contents?  What is the point of setting the window to _transparent_?

**Comment by hacker6914** [comment]
No,you dont get my point.actually i made a round corner window in pyqt5 so i need to use frameless window.there is a difference `setwindowopacity` and `translucent` background .
![Screenshot (152)](https://user-images.githubusercontent.com/67958180/98555964-8d0a5400-22c8-11eb-97d3-aaf057cf4f89.png) the transparent window set all its child widgets opacity but translucent background change only background transparent.just see the image u will notice that it is not perfectly rounded white corners are visible if i set my window to translucent window then 
![Screenshot (153)](https://user-images.githubusercontent.com/67958180/98556226-d0fd5900-22c8-11eb-87b0-60e52375e02b.png) its gone properly. so the problem is this does not make transparent to video frame in which media to be played.if u have pyqt5 then you can just run my stackoverflow code and see what happens.

**Comment by hacker6914** [comment]
whitout setting frameless and translucent background it just works fine. but i need borderless and roundcorner window where vlc only plays audio but not video.see  in the 1st one video is playing but not in second one.

**Comment by mrJean1** [comment]
Understood, thank you for explaining.  It is certainly not a `python-vlc` issue, but something at the VLC, the PyQt5 or one the O/S layers below.

**Comment by hacker6914** [comment]
It also throws a lot of error as I have mentioned in the stackoverflow but that does not affect playback why it so?

**Comment by hacker6914** [comment]
> Understood, thank you for explaining. It is certainly not a `python-vlc` issue, but something at the VLC, the PyQt5, the Qt or one the O/S layers below.

Is there any solution?

**Comment by mrJean1** [comment]
Not here at `python-vlc`.  Ask the same question at the [VLC site](https://www.videolan.org/support/) or the PyQt5/[Qt site](https://www.qt.io/qt-support/).

**Comment by hacker6914** [comment]
Why there is a method in module set_xwindow() instead of set_hwnd. I think when I set translucent background property it use x11 server as per qt doc.and if I set player_frame.set_hwnd(int(player.winId()) it forces to create a native window. Which might me a problem for playback in my opinion.And how to use that set_xwindow() cause it appears in a new window.not in my program.

**Comment by hacker6914** [comment]
![16055395320064228817297153807576](https://user-images.githubusercontent.com/67958180/99269367-4b3f5780-284c-11eb-81b9-5d98069ec086.jpg)
This is the doc for translucent window

**Comment by hacker6914** [comment]
This is the doc for for setting hand through winId()

**Comment by hacker6914** [comment]
![Uploading 16055397293604755013230225276886.jpg…]()

**Comment by hacker6914** [comment]
![Uploading 16055397931436498894824232664840.jpg…]()
This

**Comment by oaubert** [comment]
There is a set_xwindow method in the bindings because it exists in the libvlc API. Your question about this would be better asked on forum.videolan.org because it is not python-related, it is about the embedding window code of libvlc.

**Comment by hacker6914** [comment]
yes,i asked in that forum but no response then i mailed my issue to `Jean-Baptiste Kempf`(the president of the VideoLAN non-profit org) he replied that i must setting the correct COM Threading Module.here is the Screenshot
![Screenshot_20201116-122224](https://user-images.githubusercontent.com/67958180/99283425-01aa3900-285b-11eb-80a5-0f473d83b6a2.png).But I dont know how to do that?Do you know?

**Comment by mrJean1** [comment]
With respect to `set_xwindow` vs `set_hwnd` etc., take a look at the [pyqt5vlc.py](https://github.com/oaubert/python-vlc/blob/master/examples/pyqt5vlc.py) example.  That may help decide which call and what value to use.  Also, try to run that example on your particular PyQt5/Qt/Windows (?) system.

**Comment by hacker6914** [comment]
Yes I tried,at the begining it gives the below error but that doesnot affect the playback.
![Screenshot (159) - Copy](https://user-images.githubusercontent.com/67958180/99392802-4fc64780-2902-11eb-9226-078de1a00e02.png)

**Comment by hacker6914** [comment]
and then sometimes while scrolling it gives below error,not everytime
![Screenshot (159)](https://user-images.githubusercontent.com/67958180/99392901-7d12f580-2902-11eb-9926-f39a0db93d56.png)

**Comment by hacker6914** [comment]
Main problem arises if i write these 2 codes in the __init__ section(constructor) `self.setWindowFlags(QtCore.Qt.FramelessWindowHint)` and `self.setAttribute(QtCore.Qt.WA_TranslucentBackground, True) `

**Comment by mrJean1** [comment]
In a final attempt to provide _some_ help, two suggestions:

1) The last line of the `PySide2.QtWidgets.QWidget.windId()` you doc posted earlier may be important.  If the `wId` does change, it must be passed again to `set_xwindow` or `set_hwnd` for the video to be shown.  Try catching the `WinIdChange` event or get the `wId` several times at different places in your code _- especially before and after changing the window to frameless and to translucent -_ to see whether the `wId` changes.

2) There are other VLC-Qt options, like [this one](https://vlc-qt.tano.si) and there are ways to play [video in a transparent Qt window](https://stackoverflow.com/questions/59930985/displaying-a-video-with-an-alpha-channel-using-qt).  Perhaps try those to get what you're looking for.  Then apply that to your `python-vlc/VLC/PyQt5` use case.

The solution must be somewhere in `PyQt5` or `Qt` or further below and certainly _not_ in `python-VLC` nor `VLC`.

**Comment by hacker6914** [comment]
Yes,after some research, i found this is a bug in PyQt5 bacause its own mediaplayer also doesnot work on Translucent Background.So this is not a python-vlc or vlc issue.BDW Thanks.I am closing this.

**Comment by neopostmodern** [comment]
FWIW I could get the [suggested sample script](https://github.com/oaubert/python-vlc/issues/155#issuecomment-728644495) + [two inserted commands](https://github.com/oaubert/python-vlc/issues/155#issuecomment-728911966) resulting in
```
# ...
    def __init__(self, master=None):
        QtWidgets.QMainWindow.__init__(self, master)
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground, True)
# ...
```
to display transparent video on Ubuntu 22.04 + PyQt5.15 – whatever [the bug](https://github.com/oaubert/python-vlc/issues/155#issuecomment-735854376) was, maybe it's solved!
