### ISSUE TITLE
lib_vlc_new() in vlc.py is returning NoneType rathern than vlc.instance

### ISSUE THREAD

**Issue by VexenCrabtree** [oaubert/python-vlc#170]
I've been trying to fix this for weeks. I'm running 64-bit Win10, with 64-bit Powershell invoking python 3.9.2 (also 64-bit). My code runs fine for weeks on a laptop, and I'm now trying to get it work on a PC with the same setup (Win10, 64-bit VLC, 64-bit Python), but vlc.py is returning an error.

It can be reproduced in a few lines in Python:

```
PS C:\Users\Vexen\OneDrive> python
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vlc
>>> p = vlc.MediaPlayer("C\:\\Users\\Vexen\\OneDrive\\test.mp3")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Vexen\AppData\Local\Programs\Python\Python39\lib\site-packages\vlc.py", line 3327, in __new__
    o = instance.media_player_new()
AttributeError: 'NoneType' object has no attribute 'media_player_new'
>>>
```

Or, using a slightly different method with an explicit .Instance():

```
>>> import vlc
>>> i=vlc.Instance()
>>> p=i.MediaPlayer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'MediaPlayer'
```

And to test what i comes out as on the machine where it doesn't work:

```
>>> type(i)
<class 'NoneType'>
```

On the laptop where it works, it says *<class 'vlc.Instance'>*.

Here's things I've looked at and tried (more detail on each, below):

 1. The correct code required to instantiate a Media Player
 2. Using vlc.Instance('--verbose 3')
 3. vlc.py inbuilt GUI/demo causes the same error
 4. Checking that VLC can open .mp3 files
 5. Reinstalls and 64-bit checks
 6. VLC DLLs locations and the %PATH% environment variable
 7. Checking vlc.py
 8. vlc.py internal issue: Instance.__new__() call to _CFunctions returns None

(1) **Code to create the player**
---------------------------------

The docs say that .MediaPlayer automatically creates the Instance if it's not done manually. Also this is stated here: https://stackoverflow.com/questions/62453020/attributeerror-nonetype-object-has-no-attribute-media-player-new .

No matter which way I do it (direct in Python, or held open in a gui by setting frmMain.vlc to vlc.MediaPlayer(), I get the same results, so I'm only showcasing the simpler method here. Also the error occurs when running (as above) just a few lines on their in Python, so it doesn't really matter how I do it in my app.

(2) i = vlc.Instance('--verbose 3')
-------

https://stackoverflow.com/questions/46346859/python-vlc-script-error-attributeerror-nonetype-object-has-no-attribute-med says about using i = vlc.Instance('--verbose 3') to see possible error messages: Mine outputs "C:\Windows\system32" and no errors.

On the laptop where it works fine, it outputs a screenfull of technical details.

(3) **vlc.py inbuilt GUI/demo causes the same error**
-------

When looking in vlc.py I see that it's got an inbuilt simple GUI. When I run it, the file itself outputs the same error:

```
PS C:\Users\Vexen\OneDrive> python C:\Users\Vexen\AppData\Local\Programs\Python\Python39\Lib\site-packages\vlc.py C:\Users\Vexen\OneDrive\test.mp3
AttributeError: 'NoneType' object has no attribute 'media_new' (C:\Users\Vexen\AppData\Local\Programs\Python\Python39\Lib\site-packages\vlc.py 3.0.11115 vs LibVLC b'3.0.12 Vetinari')
```

This makes me think that it's something inherent to the VLC install or backend DLLs.

(4) **Checking that VLC can open .mp3 files**
-------

The following makes VLC full app open and play the file correctly:

```
PS C:\Users\Vexen\OneDrive> C:\Users\Vexen\OneDrive\test.mp3
```
Also, intentionally providing a wrong filepath to .MediaPlayer() produces the same error, therefore, it's hitting the NoneType error before it gets as far as parsing the filepath parameter.

(5) **Reinstalls and 64-bit checks**
-------

I've got 64-bit versions of Python and VLC installed. But just in case, I uninstalled it from both machines and checked for any accidental duplicate installs (there are none), and using advanced install options, done a custom install on both using the exact same settings (not including Python docs, include Tcl, include Python launcher, install for all users).

Checking Python is 64-bit on both machines:

```
>>> import platform
>>> platform.architecture()[0]
'64bit'
```

Getting a fresh vlc.py file:

```
pip3 install python-vlc --force-reinstall
```
Checking vlc version, on both machines the details match precisely:

```
PS C:\Users\Vexen\OneDrive> python -m vlc -v
vlc.py: 3.0.11115 (Sat Jul 25 15:07:40 2020 3.0.11)
LibVLC version: 3.0.12 Vetinari (0x3000c00)
LibVLC compiler: gcc version 6.4.0 (GCC)
Plugin path: C:\WINDOWS\system32
Python: 3.9.2 (64bit) Windows 10
```

And when running the VLC full app, the 'About' screen also states "3.0.12 Vetinari", on both machines.

(6) **VLC DLLs locations and the %PATH% environment variable**
-------

https://stackoverflow.com/questions/42045887/python-vlc-install-problems/47183893 and some other issues have to do with %PATH% and Python not knowing where to look for vlc DLLs, however, that's not the problem in my case.

Microsoft says that Sytem32 is a default location where Windows will search for DLLs: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order .

I've stepped through vlc.py, and in "find_lib()", I can see it picks up the correct location of libvlc.dll in /system32/. I deleted the 2x DLL files (the other is libvlccore.dll) and replaced them with newer copies from the newer install of VLC. Made no difference, but, it means that I don't need to worry about the %PATH% environment variable, because it finds the DLLs easily and automatically in /system32/.

Also, the dll version above listed by *python -m vlc -v* correctly found it in /system32/.

I've gone through Win %path% environment variable on both machines, and the user %path% var, on both machines, simplying my entire OS so that they're exactly the same, and uninstalled any other media apps that could indirectly have some kind of conflict with VLC.

(7) **Checking vlc.py**
-------

I've copied the file from the laptop (where Python can invoke VLC and play .mp3 files fine), to the desktop (where it causes an error), but with the same results. The file version looks exactly the same.

Verifying that I know exactly which vly.py is being used is used; it's in the Stacktrace of the error, and:

```
>>> vlc.__file__
```

returns the expected filepath on both machines. Copying it to the local dir doesn't change anything (except the occur occurs in the file in the new location, as you'd expect).

I also downloaded the very latest version of vlc.py from https://git.videolan.org/?p=vlc/bindings/python.git;a=blob;f=generated/3.0/vlc.py;h=fdb603002425e082b1d6b8ac08ab8322248d3ac7;hb=HEAD .

This file produces the same error on the same line of code (albeit a few line numbers different):

```
  File "C:\Users\Vexen\OneDrive\Music\Pyggy\vlc.py", line 3200, in __new__
    o = instance.media_player_new()
AttributeError: 'NoneType' object has no attribute 'media_player_new'
```

(8) vlc.py internal issue: Instance.__new__() call to _CFunctions returns None
------------------------------------------------------------------------

Fault finding in detail on vlc.py, by adding simple Print() commands, I can see that it runs find_lib() which correctly sets dll location to /system32/. The Instance class is initialized (I guess) by Instance.__new__() , which calls libvlc_new() which returns [b'vlc'], which seems good (it's not None). But it then passes this to _Cfunctions (via f()), which returns None. This is returned as the Instance() instance, and is the source of the problem.

When I added print(), I put the "Line xxxx" in the print statement, to help me remove the prints() later!:

On the PC where it doesn't work:

```
Line 4685, lib_vlc_new() is sending the following to f(): 1 [b'vlc']
Line 4688 will return the results of f(argc, argv): None
Line 1883, Instance.__new__() is returning the following: None
```

On the laptop where it does work:

```
Line 4685, lib_vlc_new() is sending the following to f():  1 [b'vlc']
Line 4688 will return the results of f(argc, argv):  <vlc.Instance object at 0x000001DCD37BA370>
Line 1883, Instance.__new__() is returning the following:  <vlc.Instance object at 0x000001DCD37BA400>
```

f is the subfunction that calls _Cfunctions.

Having done all that, I'm at a loss as to what to try next. It's hard to submit a bug report because I'm still in the situation where "it doesn't work" is the most apt description of the problem! I suppose, in particular, vlc.py isn't returning a valid Instance from the code that (I think) invokes the .dlls. But that's just "it doesn't work" with sugar coating!

**Comment by VexenCrabtree** [comment]
I'm not an advanced programmer and there's a chance I'm missing something obvious or simple so please do suggest basic stuff. But don't say I've not put in effort in trying to work it out myself!

**Comment by mrJean1** [comment]
Without having access to a Windows machine, here are a few _guesses_.

It _seems_ that on the PC, there may be a mismatch: `vlc.py` in 64-bit Python `may` be trying to load 32-bit libraries `libvlc.dll` and/or `libvlccore.dll`.

Under (6) and (8) above you mention that those `.dll`'s are found in `/system32/`.  Is that '/system32/' where _64-bit_ `.dll`'s are stored on Windows10?

Under (4) does "VLC" mean, the [VLC for Windows](https://www.videolan.org/vlc/download-windows.html) media player?  And if so, is that the 64-bit version?

Look into `vlc.py`, inside function `find_lib()` on line 112 , there is quite a bit going on from line 127 down to find the proper `.dll` file.  Right after line 129, add the following `print` statement
```
    ...
    if sys.platform.startswith('win'):
        libname = 'libvlc.dll'
        p = find_library(libname)
        print(p)
    ...
```
What does that show?

**Comment by VexenCrabtree** [comment]
Hi, thanks for the comments. Yes, for whatever reason, there is only /windows32/ even on brand-new fresh installs of Windows 64-bit. 64-bit content goes straight into /system32/. It feels wrong, but it's right!

Likewise with VLC; there are no 32-bit libraries. I have checked this by manually removing the .dlls throughout the filesystem (and verifying that indeed VLC fails to load them), and then freshly installing 64-bit version.

And finally, yet, when I say "VLC" or "VLC app", I mean the Windows 64-bit version of VLC player for Windows.

I'll try the print statement and let you know the result... after cooking dinner :-)

**Comment by mrJean1** [comment]
Bon appetit!

**Comment by VexenCrabtree** [comment]
**Results** (and I added bits):

PS C:\Users\Vexen\OneDrive\Music\Pyggy> python
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vlc
Line 127 - Print sys.platform: win32
Line 130 - What is p? C:\WINDOWS\system32\libvlc.dll

**Comment by mrJean1** [comment]
That is a 64-bit .dll in /system32/? 

Is there a /system64/ directory on the PC?

Can you do the same on the laptop?

**Comment by VexenCrabtree** [comment]
Results on the laptop, where it works:

Line 206: What are find_lib() return vals? <CDLL 'C:\WINDOWS\system32\libvlc.dll', handle 7ffe4c320000 at 0x2d171f30070> C:\WINDOWS\system32

It seems this is a positive test of this function on both machines. I also done these tests (with slightly different prints), and next moved on to def libvlc_new() (line 4685); the results are in section #8 of the original post, for both machines.

**Comment by mrJean1** [comment]
OK, the print statement is to make sure that p is not None.  Is that true on the laptop too?

If it is, then it is not any of the other code in find_lib() which tries to find the .dll’s.

Most important, if both the PC and laptop show the same non-None result for p, there is nothing in vlc.py which causes the difference in behavior between the PC and laptop.  There must be something else, somewhere else.

Back in 45 minutes.

**Comment by VexenCrabtree** [comment]
Thanks for keeping at it with me. When it comes to libvlc_new() and its internal f=_Cfunctions.get part, the code was beyond me, and I could no longer work out what was going on. On the laptop, f() returns an object, but on the desktop it returns None. This, as far as I can tell, is the source of problem. And it may well be, as you say, that it's the .dll that's to blame and not python-vlc, but, I don't have the skills to know for sure.

**Comment by mrJean1** [comment]
My suspicion still is that something is wrong or different with VLC or libvlc.dll or Python’s module called ctypes (the latter is the “connector” between Python and the libvlc.dll once loaded).

One other thing to try ... are the libvlc.dll files the same on both the PC and laptop?  How large is the /system32/libvlc.dll file on both?  Type something like “dir ...libvlc.dll” in a command or PowerShell window on both.

**Comment by mrJean1** [comment]
Your diagnosis of the problem is correct, the result of the `f()` call is `None`.  The question is why is it `None` on the PC and not on the laptop?

That `f()` call goes via `ctypes` straight into the `libvlc.dll`.  The root cause for the difference must be some difference in `VLC`, `libvlc.dll` or `ctypes` as mentioned before.  Not giving up yet.

**Comment by VexenCrabtree** [comment]
(a+b+c+d) I've not only checked that vly.py and libvlc.dll are the same (and the other lib vlc core.dll), once, I directly implanted them from the laptop to the desktop to ensure that something about the install process wasn't messing them up somehow on the PC. 
(e) The results from python -m vlc.py -v are exactly the same on both (section #5; I've rechecked a few times too, especially after resintalls.
(f) Checking find_lib output (the print of the return values) I did already do; although I didn't show it in section #8, because it led on to the Instance._ _ new _ _() checks., which is where the differences started. find_lib definitely shows the same /system32/ dir on both machines.

......... aaaaaaannnnnnddddd..... it works.

**Comment by VexenCrabtree** [comment]
I don't know what is was, or if "5 restarts" was suddenly the magic number, or what, but suddenly today, it has started working on the main PC. Once difference (on both the laptop at the PC) is that the DLL is now loading from "C:\Program Files\VideoLAN\VLC\libvlc.dll" rather than the /system32/ directory. I strongly suspect that within Windows somewhere, the .dll was cached by something like the preload process or some other obscure bit of windows. There's no user-facing way to clear some of Windows internal caches. And that's only a guess.

**Comment by VexenCrabtree** [comment]
It's going to hurt that we're not really found the issue, but, on the plus side, this thread is a good piece of documentation for a whole load of things that others might want to check if facing install-style-issues for python-vlc / Python / VLC.

**Comment by VexenCrabtree** [comment]
And if the PC suddenly stops working as mysteriously as it started, I'll be back. Until then, **I thank you for your time and effort**. It's going to hurt that we're not really found the issue, but, on the plus side, this thread is a good piece of documentation for a whole load of things that others might want to check if facing install-style-issues for python-vlc / Python / VLC.

**Comment by VexenCrabtree** [comment]
If you're a StackOverflow user, post some kind of answer here https://stackoverflow.com/questions/66377541/why-is-vlcs-py-modue-returning-nonetype-in-media-player-new and I'll mark it as the official correct-answer. I don't think there's an equivalent here. I'll "Close with comment" on this thread in a day or so (I'm not sure if you can reply after I've done so).

**Comment by mrJean1** [comment]
Glad we got this far!  One of the Microsoft sites mentioned that if a `.dll` is already loaded in memory Windows will use that.  That is very much like caching that library, indeed.  Rebooting the PC cleared that, certainly.

It is no longer possible to find out which `libvlc.dll` was actually loaded.  A likely scenario is that even though inside `vlc.py` function `find_lib`, `ctypes`' `p = find_library(libname)` finds the `C:\...\system32\libvlc.dll` file, at the very end of `find_lib` the line `dll = ctypes.CDDL(p)` did not load that `.dll`.  Instead, it the cached one was returned by Windows to `ctypes` and `vlc.py`.

Sorry, I am not a StackOverflow user.  Why not put a comment there and refer to this very issue #170 with this url `https://github.com/oaubert/python-vlc/issues/170`.

**Comment by VexenCrabtree** [comment]
Thanks again, take care.

**Comment by OneMadGypsy** [comment]
I was just messing around with getting the python vlc bindings to work without installing vlc. In that, I believe I found a solution to your problem.

`os.environ.setdefault('PYTHON_VLC_LIB_PATH', path/to/libvlc.dll)`

Set the above before importing vlc. Essentially, you are manually setting `path_lib`.

**Comment by suelliton** [comment]
I'm having this error, i'm in linux system, i tested a lot of things but dont resolved.

**Comment by mrJean1** [comment]
Please type “`python vlc.py -h`” and post the output.

**Comment by suelliton** [comment]
@mrJean1  I achieved resolve the problem, copying the vlc.py to main directory of my project, this file can be found in "/home/YOURUSERNAME/.local/lib/python3.12/site-packages", and in terminal i runned  $export VLC_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vlc/plugins/ . Maybe this dont is necessary because the code above make exactly this.

And in my code of use the vlc intance i put:
plugin_path = '/usr/lib/x86_64-linux-gnu/vlc/plugins'
os.environ.setdefault('VLC_PLUGIN_PATH', plugin_path)

Remember that diferents system can have diferents paths to the plugins vlc, then, after theses commands magically the build with flet and  pyinstaller, and using auto-py-to-exe works fine, i dont tryed run the executable in another computer, then is a provisory solution, i encontred a complete solution that modify the path in vlc.py, in the end of this issue, https://github.com/pyinstaller/pyinstaller/issues/4506 , but i dont tested for while..
