### ISSUE TITLE
How to get frame from running video like Android Mini player/Youtube's Mini player while use trackbar in python vlc?

### ISSUE THREAD

**Issue by hacker6914** [oaubert/python-vlc#171]
![Screenshot (11)](https://user-images.githubusercontent.com/67958180/112754292-458f1680-8f90-11eb-9cb5-5198e4dce807.png)
Hi, I want to make a mini frame with slider that show preview of frames like above image in my video player python.Is there any way to extract those frame and render into small screen while playing video?

**Comment by oaubert** [comment]
There is an API for this in the development version of libvlc, which is wrapped in the [corresponding version of the python bindings](https://github.com/oaubert/python-vlc/tree/master/generated/dev). If you want to test this API, you will have to install a snapshot dev version of vlc.

**Comment by hacker6914** [comment]
It gives this error
File "f:/pc2/proj/Pyqt Projects/file fider/CustomVideoPlayer.py", line 406, in second_time_change
    image=self.media.thumbnail_request_by_time(val,1,100,100,1,"chromecast",1000)
  File "f:\pc2\proj\Pyqt Projects\file fider\Vlc.py", line 2693, in thumbnail_request_by_time
    return libvlc_media_thumbnail_request_by_time(self, time, speed, width, height, crop, picture_type, timeout)
  File "f:\pc2\proj\Pyqt Projects\file fider\Vlc.py", line 5572, in libvlc_media_thumbnail_request_by_time
    MediaThumbnailRequest, Media, ctypes.c_longlong, ThumbnailerSeekSpeed, ctypes.c_uint, ctypes.c_uint, ctypes.c_bool, PictureType, ctypes.c_longlong)
NameError: name 'MediaThumbnailRequest' is not defined

**Comment by oaubert** [comment]
I never used this API, I do not have the time to follow and test the dev VLC. I merely adapt the bindings generator so that it should output working code. You can try to add the following declaration in vlc.py (near the Log_ptr definition):
```
class MediaThumbnailRequest(ctypes.POINTER):
    pass
```
it should define the needed  MediaThumbnailRequest structure.

**Comment by mrJean1** [comment]
FWIIW,

`vlc.py` 3.0.11115 built on _Jul 25, 2020_ did have a `class MediaThumbnailRequest` defined on line 1289.  But that is no longer present in `vlc.py` 3.0.11115 from _Jan 10, 2021_.

An other, separate issue is that there is no definition for `libvlc_media_thumbnail_request_by_time` anywhere in either `vlc.py`.

**Comment by oaubert** [comment]
Indeed. It was removed in 73a20147565c80667b7706d4c4a3b4dccda9a5f4 (not surprising, this was a big change that had potential to break things). I  put it back in the header.py file, but before regenerating a new vlc module, I have to finish integration of #109 and fix a regression. Given my time constraints these days, there will be some delay.

**Comment by Hannah-GBS** [comment]
Any word on this?

**Comment by oaubert** [comment]
It has been fixed in 1f8fc6d4203473f2ee2207faae90bc8e170376fe and the latest pypi release  3.0.12118 includes it.

**Comment by hacker6914** [comment]
Yes.Now it returns MediaThumnailRequest type object.then how to extract those images.I mean how to save to directory or show in a Label for GUI application?

**Comment by Hannah-GBS** [comment]
Yeah, I'm not sure this is usable as is, without bindings for [libvlc_media_get_thumbnail_request_by_time()](https://videolan.videolan.me/vlc/group__libvlc__media.html#ga96594d719fc20364a2cbc0981877a55e) or [libvlc_media_get_thumbnail_request_by_pos()](https://videolan.videolan.me/vlc/group__libvlc__media.html#ga935c84826158fc9d50f534b5c2da72d6) unless I'm misunderstanding something

**Comment by hacker6914** [comment]
Then what to do? @Hannah-GBS  @oaubert

**Comment by Hannah-GBS** [comment]
To be honest, even using the dev-build of libvlc 4.0, I'm stuck. I have a request using 'media.thumbnail_request_by_pos()', and I'm subscribed to the 'MediaThumbnailGenerated' event and can see it fires, but I'm not sure how to actually get the thumbnail from that.
