### ISSUE TITLE
Some attributes missing or prefixed

### ISSUE THREAD

**Issue by Neraste** [oaubert/python-vlc#174]
In the documentation and in version 3.0.11115, `MediaTrack` objects have the following public attributes:

```
audio
bitrate
codec
description
id
language
level
original_fourcc
profile
subtitle
type
u
video
```

In version 3.0.12117 (using VLC 3.0.12 on Linux and Windows), some of them have disappeared, or are prefixed with `i_`:

```
i_codec
i_original_fourcc
i_id
i_type
i_profile
i_level
audio
video
subtitle
```

Same goes for `AudioTrack` objects:

```
channels
rate
```

became:

```
i_channels
i_rate
```

And for `VideoTrack` objects, trying to access attributes with IPython leads to a segmentation fault.

I don't think all of this was voluntary.

**Comment by oaubert** [comment]
This is not a trivial issue in fact: in previous (pre- 3.0.11115) versions, all libvlc structs mapping to objects was hand-defined, which lead to issues when updating things, and also in handling variations between different versions of libvlc. I switched to automatic generation of struct mapping, which has the side-effect of using the exact same field names  as in the C API (hence the i_ prefixes). 

Docs should be at least updated, but then it used epydoc until then, which has been deprecated for a  long time. So this is a great opportunity to move from the obsolete epydoc to a more current tool like pydoctor, or even work on integration with readthedocs tooling. But some tweaks are needed, the current output is not complete and should be fixed before being able to update the docs. If anyone wants to work on this, one just has to `make doc` in the bindings source directory, and see the output in `doc`.

**Comment by Neraste** [comment]
I see. So, for the long run, the `i_` prefixed names will remain? This makes existing code based on this lib to break, which is unexpected as this change was introduced by a patch release.

I will see if I can do something for the doc.

**Comment by oaubert** [comment]
You are right. Given the versioning scheme used, based on vlc, I cannot control the major release number of the bindings (which is vlc major number). I will then refrain from a too large breaking change, and will strip prefixes in the 3.x series at least, to preserve compatibility. And think about the most appropriate approach for the 4.x libvlc release.
