### ISSUE TITLE
how to debug

### ISSUE THREAD

**Issue by lion6230i** [oaubert/python-vlc#18]
Hi ,

I porting vlc library to mips platform and use vlc.py to test.
But have some error.
# python vlc.py
Usage: vlc.py [options] <movie_filename>
Once launched, type ? for help.

Build date: Fri Oct  7 12:04:48 2016 (0x0)
Error: no function 'libvlc_get_version'

Could any one suggest me how to debug?
I have confirm libvlc.so have libvlc_get_version function.

**Comment by oaubert** [comment]
Hi

You should first try the basic loading of the vlc lib from a python
interpreter:

import ctypes
from ctypes.util import find_library
p = find_library('vlc')
dll = ctypes.CDLL(p)
dll.libvlc_get_version()

and see if it works.

Olivier

**Comment by lion6230i** [comment]
Hi Olivier,
Thanks for your reply.
I try the command step by step ,

> # python
Python 2.7.6 (default, Nov 16 2016, 11:18:53) 
[GCC 4.7.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> from ctypes.util import find_library
>>> p = find_library('vlc')
>>> dll = ctypes.CDLL(p)
>>> dll.libvlc_get_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/python_nfs/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/media/python_nfs/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: Unable to resolve symbol

Is it mean python can't find my libvlc.so ?
I have set LD_LIBRARY_PATH before I run python.

**Comment by oaubert** [comment]
python seems to find libvlc.so (else it would fail at the ctypes.CDLL
line). Maybe your symbol names are mangled in the lib ? You should
check with 
readelf -Ws /path/to/libvlc.so
or
objdump -TC /path/to/libvlc.so

If the symbol information is correct, then maybe it has to do with the
arch. You should then investigate ctypes on mips, by for instance
building a minimal lib with a unique symbol.

Olivier

**Comment by lion6230i** [comment]
Hi Olivier,

I dump symbol information in library , it's correct.

> [root@localhost lib]# objdump -TC libvlc.so|grep vlc_get_version
00005954 g    DF .text	00000018  Base        libvlc_get_version


Then  I try the command in below:

> 
# python
Python 2.7.6 (default, Nov 16 2016, 11:18:53) 
[GCC 4.7.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import *
>>> cdll.LoadLibrary("libc.so.0")
<CDLL 'libc.so.0', handle 43d838 at 2b396410>
>>> libc = CDLL("libc.so.0")
>>> libc.printf
<_FuncPtr object at 0x2b38b260>
>>> libc.printf("lion debug")
lion debug10

Does it mean ctypes work fine on mips?

**Comment by oaubert** [comment]
So it seems ctypes is working on mips, and you have the correct symbol
in libvlc. Maybe the ctypes.util.find_library does not find the
appropriate library, could you check the output?

Olivier

**Comment by lion6230i** [comment]
Hi Olivier,

You are right. The problem case by find_library.
I modify vlc.py skip find_library step , load libvlc.so directly. 
Then test it , it's works fine.

> # python vlc.py
lion debug 1
Usage: vlc.py [options] <movie_filename>
Once launched, type ? for help.

Build date: Fri Oct  7 12:04:48 2016 (0x0)
LibVLC version: 2.2.4 Weatherwax (0x2020400)
LibVLC compiler: gcc version 4.7.3 (Buildroot 2013.08-00907-ga7254e1)

I think , it's may cause by my platform do not have ldconfig.
Somebody said find_library will use ldconfig to look up where library can load.
Anyway thanks for your support.
