### ISSUE TITLE
Can I change the background color in fullscreen mode?

### ISSUE THREAD

**Issue by cdragicevic** [oaubert/python-vlc#180]
Hi, is there a way to set background color (for example grey) when playing in fullscreen mode, supposing the video is smaller than the screen pixel dimensions?

Has this something to do with Marquee option. I am new with python-vlc.

Also, is there a way to play and repeat (loop) a video?

Do the preferences in VLC sofware extend to python-vlc?

**Comment by mrJean1** [comment]
Re the marquee color, that sets the color of the text in a marquee.

There is no VLC option to set the background color.  But there may be a way to do that using the underlying OS/Windows system.

Not sure about the loop and preferences, sorry.

**Comment by oaubert** [comment]
AFAIK, vlc preferences are not  used when using libvlc (hence python-vlc). For the looping question, the current libvlc API does not offer this (I think it is planned for libvlc4). You can see a workaround at https://forum.videolan.org/viewtopic.php?t=132149
