### ISSUE TITLE
Does the VLC Python binding read the preferences file?

### ISSUE THREAD

**Issue by project-owner** [oaubert/python-vlc#188]
According to the VLC doc:
https://wiki.videolan.org/Preferences/
the preferences file is located on Linux here:
~/.config/vlc/vlcrc
But I don't see that file after installing VLC and Python binding on Linux (Raspberry Pi).
Does the VLC Python binding read the preferences file? If so, where does it get it?
Thanks!

**Comment by oaubert** [comment]
The preferences file is for the VLC binary, not the libvlc API. The VLC binary itself does not even use the libvlc API. So no, there is no configuration file. If you need to have specific options/parameters you need to specify them as command line parameters when instanciating `vlc.Instance`
