### ISSUE TITLE
Better Error Output

### ISSUE THREAD

**Issue by elibroftw** [oaubert/python-vlc#205]
Currently I'm getting "Cannot load lib specified by PYTHON_VLC_LIB_PATH env. variable." 

I had to edit the python-vlc to print the OSError and finally got "libvlccore.so.9: cannot open shared object file: No such file or directory"

**Comment by oaubert** [comment]
Actually  it seems more explicit to me to indicate that the path is taken from the PYTHON_VLC_LIB_PATH environment variable (and you just have to display its value to know the filename).

**Comment by elibroftw** [comment]
I specified the path to libvlc but libvlc looks for libvlccore. I shouldn't have had to edit the library to print out an oserrror to figure out the problem.

The solution was to os.chdir into the vlc libs path and then import vlc. There's simply too much hacking needed to get it working...
