### ISSUE TITLE
Program throws exception when trying to add an event callback

### ISSUE THREAD

**Issue by Gabryx64** [oaubert/python-vlc#210]
Program throws "Exception function has keyword-only parameters or annotations, use inspect.signature() API which can support them" when I try to add an event callback.
I fixed this by changing
```python
if not any(getargspec(callback)[:2]):  # list(...)
            raise VLCException("%s required: %r" % ('argument', callback))
```
to
```python
if not any(getfullargspec(callback)[:2]):  # list(...)
            raise VLCException("%s required: %r" % ('argument', callback))
```
in `vlc.EventManager.event_attach()`

Is there i way I could fix this without actually modifying the library?

**Comment by mrJean1** [comment]
A patch is forthcoming to keep `getargspec` for Python 2 and use `getfullargspec` or `signature.parameters` in Python 3.

**Comment by mrJean1** [comment]
Actually, the patch is already in the `generator/template/header.py` and `-/override.py` files, see function `len_args`.  The `generated/vlc.py` file needs to be regenerated.
