### ISSUE TITLE
Is there a way to make the player switch track when the previous one has ended?

### ISSUE THREAD

**Issue by Gabryx64** [oaubert/python-vlc#211]
Is there a way to make the player switch track when the previous one has ended?
I tried to implement this feature using events, but events callbacks are called on a different thread than the main one, so I can't switch tracks in the callback function's body

**Comment by oaubert** [comment]
The libvlc API is not re-entrant (i.e. you cannot call libvlc functions directly from libvlc event handlers). This is a libvlc limitation. Depending on the framework/mainloop you are using, you should use their mechanism to make sure actions are called from the main loop, see for instance https://forum.videolan.org/viewtopic.php?t=130714#p440116
