### ISSUE TITLE
Python Bindings newbie

### ISSUE THREAD

**Issue by zuhi** [oaubert/python-vlc#22]
Hello,
I started with Python Bindings for the first time with:
operating system- ubuntu 14.04
vlc-1.1.2 and python-2.7.6
Here is the sample code I am working on 

 ` 

    import vlc 
    instance = vlc.Instance()
    media_ply = instance.media_player_new()
    media_ply.set_mrl("test1.mp3")
    media_ply.play()

 ` 
When I execute this code I get the error message as 

`

     Traceback (most recent call last):
     File "vlc1.py", line 3, in <module>
     instance = vlc.Instance()
     File "/home/ankita/env2/mmenv5/local/lib/python2.7/site-packages/vlc.py", line 1551, in __new__
     return libvlc_new(len(args), args)
     File "/home/ankita/env2/mmenv5/local/lib/python2.7/site-packages/vlc.py", line 3903, in libvlc_new
     ctypes.c_void_p, ctypes.c_int, ListPOINTER(ctypes.c_char_p))
     File "/home/ankita/env2/mmenv5/local/lib/python2.7/site-packages/vlc.py", line 246, in _Cfunction
     raise NameError('no function %r' % (name,))
     NameError: no function 'libvlc_new'

`
Did I do something wrong?

**Comment by ZachaRuba** [comment]
This is one newbie talking to another.
**I would recommend that you update your current version of VLC**
why?
That error means that the funciton `libvlc_new` is missing.

Below, the function is clearly defined by `vlc.py`
![image](https://cloud.githubusercontent.com/assets/16966433/21579698/ae75bfe8-cf71-11e6-971f-8d6d322b2ee0.png)

But all this function does is attempt to call the function `libvlc_new` from the VLClibrary you installed with VLC your current version of VLC. 

In the README.rst

> The same module should be compatible with various versions of libvlc 2.*. However, there may be incompatible changes between major versions. A 2.2 specific binding is provided.

The lastest version of VLC is 2.2.4 so **I would recommend that you update your current version of VLC** which should update your library as well.

**Comment by oaubert** [comment]
Yes, you have a seriously outdated vlc. 1.2.0 was released more than 5 years ago. Please update it.
