### ISSUE TITLE
OSError on MacOS M1 machine

### ISSUE THREAD

**Issue by gulaki** [oaubert/python-vlc#226]
`>>> import vlc`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/Users/username/opt/anaconda3/envs/conda-env/lib/python3.10/site-packages/vlc.py", line 220, in <module>
    dll, plugin_path  = find_lib()`
`  File "/Users/username/opt/anaconda3/envs/conda-env/lib/python3.10/site-packages/vlc.py", line 192, in find_lib
    ctypes.CDLL(c)`
`  File "/Users/username/opt/anaconda3/envs/conda-env/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)`
`OSError: dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib, 0x0006): tried: '/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/Applications/VLC.app/Contents/MacOS/lib/libvlccore.9.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))`

**Comment by mrJean1** [comment]
Looks like this is `python 3.10` built for `Intel` and the `libvlc` verson for `arm64` (i.e. Apple Silicon).  Try
```
 python3.10 -c "import platform; print(platform.machine())"
```
If that shows `arm64`, try installing the [macOS 64-bit universal2](https://www.python.org/downloads/release/python-3107/) build of `python 3.10`.  And/or get the `universal2` built of [VLC 3.10.16+](https://www.videolan.org/vlc/download-macosx.html).

**Comment by mrJean1** [comment]
Look like this is `python 3.10` built for `Intel` and `VLC/libvlc` for `arm64` (i.e. Apple Silicon).  Try to run
```
python3.10 -m vlc --version
```
and
```
python3.10 -c "import platform; print(platform.machine())" 
```
If that shows 'x86_64`, install the [Mac Universal Binary of VLC 3.10.16+](https://www.videolan.org/vlc/download-macosx.html).

**Comment by mrJean1** [comment]
Here are some combinations of Python** and `VLC/libvlc` builds tested (on macOS 12.8 and M1 Apple Silicon with `cocoavlc.py`):

- `python 3.8.10 Intel`: works with `VLC 3.0.16 Universal` and `VLC 3.0.12 Intel`, fails with `VLC 3.0.16 Apple Silicon`.

- `python 3.10.7 universal`: works with `VLC 3.0.16 Universal` and `Apple Silicon`, fails with `VLC 3.0.12 Intel` (with the same error messages as above).

Installing the [Mac Universal Binary of VLC 3.0.16+](https://www.videolan.org/vlc/download-macosx.html) should avoid the errors.

However, playing a video with `vlc.py` on macOS _does not work_, no video will be shown.  Use one of the [examples](https://github.com/oaubert/python-vlc/tree/master/examples) like `cocoavlc.py` or `tkvlc.py`.

__
**) The Python builds used are downloaded from [Python.org](https://www.python.org/downloads/macos/).

**Comment by gulaki** [comment]
Installing the Mac Universal Binary from the provided link above fixes the error. Thank you.
