### ISSUE TITLE
Can I stream mp4 from a stream of bytes?

### ISSUE THREAD

**Issue by thoithoi58** [oaubert/python-vlc#228]
Hi,

I have a project which reverse engineer to send a request to a server, then the server response back a mp4 file chunk by chunk (in bytes format, and different size of course). So I want to open a VLC instance and pass the chunk to that instance so I can watch it in real time rather than save it to local disk and playback later.

Can I do this using this library, thanks in advance!

**Comment by oaubert** [comment]
Yes, it can be done. The #227 bug should help you for this.
