### ISSUE TITLE
wxplayer example errors

### ISSUE THREAD

**Issue by ZachaRuba** [oaubert/python-vlc#23]
Hello,
I am running python 3.5.2 on windows 10.  VLC version 2.2.4 Weatherwax.
Tried out your wxplayer example but didn't work so well.
The audio files come through but the video doesn't. The following error pops up:

> core video output error: video output creation failed
> core decoder error: failed to create video output

Any ideas?  I imagine it has something to do with the type of video output

**Comment by oaubert** [comment]
Hi
Looking at the wxplayer code, I would guess that it is not adapted to windows (yet). In line 140 https://github.com/oaubert/python-vlc/blob/master/examples/wxvlc.py#L140 the set_xwindow() API is used, which is meant for X-Window systems. Could you try to adapt the corresponding code from qtvlc.py to use the set_hwnd API (for Windows) and report on your success (or better yet, submit a patch :-) ?

**Comment by ZachaRuba** [comment]
Hello again Oliver!
Yes, the set_hwnd API did work on my windows system!
I edited the example so it should work on both windows and linux
I made a few modifications to the example:

1. removed `import user` from line 35

2. changed lines 122, 123 to
`userhome = os.path.expanduser('~')`
`dlg = wx.FileDialog(self, "Choose a file", **userhome**, "", "*.*", wx.FD_OPEN)`

supposedly `os.path.expanduser('~')` should find the user home directory on both
windows and linux (and mac?).  [ref](http://stackoverflow.com/questions/2668909/how-to-find-the-real-user-home-directory-using-python)

3, Changed line 140 to
`if os.name == 'nt':`
           ` self.player.set_hwnd(self.videopanel.GetHandle())`
`else:`
           `self.player.set_xwindow(self.videopanel.GetHandle())`

os.name will come up as 'nt' for any OS that isn't unix based (AKA windows). That means that it will
attempt to use the xwindow handle on a mac but that should be fine yeah?

**Comment by ZachaRuba** [comment]
2 more things that could be improved.

Python 2.x has the unicode() function.
Python 3.x doesn't include the unicode() function since all strings are unicode in python3.x so you get an error.

line 129, I just added something like;
`# Creation`
`            try:  # Python 3.x`
`                self.Media = self.Instance.media_new(`
`                    os.path.join(dirname, filename))`
`            except SyntaxError:  # Python 2.x`
`                self.Media = self.Instance.media_new(`
`                    unicode(os.path.join(dirname, filename)))`
`            except:  # fails if python version unknown`
`                raise`

And then I think that this has something to do with the version of wx the user has.
Line 124,
My version of wx required the `wx.FD_OPEN` instead of `wx.OPEN`
once again a try statement or something similar
