### ISSUE TITLE
Wrapper for struct libvlc_event_t is Error

### ISSUE THREAD

**Issue by shq2333** [oaubert/python-vlc#253]
Wrapper for struct libvlc_event_t is Error.
https://github.com/oaubert/python-vlc/blob/c91837339d8161b00dd59885eebdc07765d557c9/generated/3.0/vlc.py#L1095-L1104
Also on [https://pypi.org/project/python-vlc/](https://pypi.org/project/python-vlc/) **version 3.0.18121**
The version **3.0.11115** is correct.
[version 3.0.11115](http://olivieraubert.net/vlc/python-ctypes/doc/vlc-pysrc.html#Event)

**Comment by oaubert** [comment]
Thanks for spotting this and the precise report. I have identified the issue and the fix is almost ready.
