### ISSUE TITLE
Render to custom OpenGL texture

### ISSUE THREAD

**Issue by bl1nch** [oaubert/python-vlc#258]
Hello. Vlc 4.0 added the ability to render video into a custom opengl texture. Can you please find out if python-vlc supports this function. If so is there any example of using this? If not, will this be implemented in the future? Thanks in advance for your answer.

**Comment by oaubert** [comment]
https://gist.github.com/dgfitch/02b40ec77d12cc6ca11a81360de9f2ab

**Comment by oaubert** [comment]
These functions are blacklisted because their signature and parameter types makes it not that easy to define automatic conversion to ctypes. If you want, you can contribute the appropriate ctypes wrapper definitions, I will gladly integrate them in the module.
