### ISSUE TITLE
log methods signature mismatch

### ISSUE THREAD

**Issue by yan123** [oaubert/python-vlc#27]
**Version:** 1dd9bf6c31d00b74a05b21731a859f1a4f3ab255
Python 2.7.6
Ubuntu 14.04 (LTS)

Generated vlc.py (tried both the one available in /generated/ dir and the one re-created by generate.py script) contains method definitions:
https://github.com/oaubert/python-vlc/blob/master/generated/vlc.py#L1841
https://github.com/oaubert/python-vlc/blob/master/generated/vlc.py#L4402

that do not match actual library signature: http://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__log.html#ga67e824ebbd01c037fd877fba5fa4131c

and do not match the code:
https://github.com/oaubert/python-vlc/blob/master/generated/vlc.py#L4398-L4399

**Actual params:** (cb, data, p_instance)
**Expected params:** (p_instance, cb, data)

**Comment by oaubert** [comment]
Thanks for the detailed report. It comes from missing parameter names in the include definitions. I have fixed it in the vlc tree and will generate new bindings soon.
