### ISSUE TITLE
Cannot parse a media

### ISSUE THREAD

**Issue by gri38** [oaubert/python-vlc#29]
# My purpose
is to get an audio file length without using the vlc player (because it may be playing another file).

So I want to parse the media, so I can call get_duration (without parsing, it returns -1, as expected).

But:
 - I don't have the synchronous parse function on the Media class.
   _https://www.olivieraubert.net/vlc/python-ctypes/doc/vlc.Media-class.html#parse_
 - Media::parse_with_options doesn't seem to work
   _https://www.olivieraubert.net/vlc/python-ctypes/doc/vlc.Media-class.html#parse_with_options_

# My config
VLC version 2.2.4 Weatherwax (2.2.4-0-g888b7e89)
Windows 8
Compiler: gcc version 4.9.2

Python 2.7.13

vlc.py: __version__ = "N/A"
build_date = "Wed Mar 1 18:03:15 2017"

# A sample of code to ease

```
import vlc
i = vlc.Instance()
media = i.media_new("C:\\a.flac")
media.get_duration()
-1L  
```
 **=> OK, because not parsed yet**

```
media.parse() 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Media' object has no attribute 'parse'
```
 **=> "_OK_", not in the bindings.**
```
media.parse_with_options(0, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "vlc.py", line 2455, in parse_with_options
    return libvlc_media_parse_with_options(self, parse_flag, timeout)
  File "vlc.py", line 5224, in libvlc_media_parse_with_options
    ctypes.c_int, Media, MediaParseFlag, ctypes.c_int)
  File "vlc.py", line 254, in _Cfunction
    raise NameError('no function %r' % (name,))
NameError: no function 'libvlc_media_parse_with_options'
```
 **=> Why? And how to parse the media to have its duration.**

# Many thanks
For this python binding and all your work (API doc, ...) it's so easy to play music. Thanks guys!

**Comment by oaubert** [comment]
It was indeed a bug in the parser code, now fixed.

**Comment by gri38** [comment]
Thank you very much. Fix was sooo fast. And it works.
