### ISSUE TITLE
Missing event for metadata change

### ISSUE THREAD

**Issue by project-owner** [oaubert/python-vlc#30]
While playing web radio stream there is no event issued indicating the change of Meta.NowPlaying which is usually track title. There is a workaround - attach callback for MediaPlayerTimeChanged and call  media.get_meta(Meta.NowPlaying). But this is unnecessary polling.

**Comment by oaubert** [comment]
I would guess that Meta.MediaMetaChanged should do the trick. If it does not, please report to the VLC issue tracker https://trac.videolan.org/vlc since the python bindings merely wrap the libvlc API, and this issue should be solved at the libvlc level.
