### ISSUE TITLE
Choose which libvlc to use?

### ISSUE THREAD

**Issue by Neraste** [oaubert/python-vlc#31]
Hi

I have VLC 2.2.4 on my system, using libvlc5. I have also vlmc for testing, using libvlc6 (for VLC 3). The problem is that the Python-VLC binding seems to use the latest libvlc available, which causes some sneaky problems (eg: using libvlc6, instance is `None` without warnings).

Is there a way to choose the libvlc version to use?

Thanks for your time

**Comment by oaubert** [comment]
It depends on your OS. Look for the find_lib() function at the beginning of the module, it is where it tries to locate the appropriate lib. There could indeed be some environment variable that could allow to override this.

**Comment by Neraste** [comment]
Thanks, dude!
