### ISSUE TITLE
tutorial?

### ISSUE THREAD

**Issue by qinst64** [oaubert/python-vlc#33]
Where can I find a full tutorial/reference for commands/api? cannot find it anywhere. e.g. get the length of music etc

**Comment by oaubert** [comment]
The reference documentation can be found at https://www.olivieraubert.net/vlc/python-ctypes/
For tutorials, http://forum.videolan.org/ and stackoverflow are good starting points. If you are interested in writing a tutorial, I can give some help and we could host it on the github wiki.
