### ISSUE TITLE
"error: package directory 'generator/generate' does not exist

### ISSUE THREAD

**Issue by Enadeia** [oaubert/python-vlc#34]
Hello,

I tried to install the Python binding library, I had an error message : "error: package directory 'generator/generate' does not exist.

- ![image](https://user-images.githubusercontent.com/32996556/31859555-c653be9c-b70d-11e7-8319-f9f243cb5c2e.png)

But I can find the folder and file mentioned:

- ![image](https://user-images.githubusercontent.com/32996556/31859575-2414ea2e-b70e-11e7-97e9-513555623e0a.png)

I really can't understand why I have this error message.

Would you have an idea? It would really help me. Thanks!

**Comment by oaubert** [comment]
If you want to install the vlc module, then you should not use the setup.py file from the root of the repository, but rather from the generated/2.2 directory. The root one corresponds to the code-generator that generates the module. The generated/2.2 (or 3.0) is for the actual vlc module, and what is used to upload to PyPI.
