### ISSUE TITLE
Some files sound like white noise

### ISSUE THREAD

**Issue by project-owner** [oaubert/python-vlc#35]
I'm using the latest version of the binding on Raspberry Pi 3. Some files sound like white noise.
Here is example:
http://www.archive.org/download/aesop_fables_volume_one_librivox/fables_01_08_aesop_64kb.mp3
It has the following parameters:
Codec MPEG Audio layer 1/2(mpga)
Channels: Stereo
Sample rate: 22050 Hz
Bitrate: 64 kb/s

Another files with different parameters work fine. For example:
http://www.archive.org/download/aesop_fables_volume_one_librivox/fables_01_09_aesop_64kb.mp3
Codec MPEG Audio layer 1/2(mpga)
Channels: Mono
Sample rate: 44100 Hz
Bitrate: 64 kb/s

I'm just wondering if this is VLC/binding issue or hardware/driver issue while playing files with
sample rate 22050 Hz ?
Thanks!

**Comment by project-owner** [comment]
Got the answer:
https://support.hifiberry.com/hc/en-us/community/posts/115004271729-Some-files-sound-like-white-noise?page=1#community_comment_115002095849

**Comment by project-owner** [comment]
Is it possible to convert stream with 22kHz to 44.1kHz on the fly using VLC/binding ? For example, detect the bitrate and if it's 22 then start conversion.

**Comment by oaubert** [comment]
Probably, but you should ask forum.videolan.org for this, it is not specific to the  python bindings and you will get more feedback.
