### ISSUE TITLE
add_slave Media_Player and slaves_add Media

### ISSUE THREAD

**Issue by hamed169** [oaubert/python-vlc#36]
`        psz_uri = ''`
`        try:`
`            self.media_player.add_slave('mySrt.srt', psz_uri, True)`
`        except Exception as e:`
`            print('{}: {}'.format(type(e), e))`
`
`<class 'NameError'>: no function 'libvlc_media_player_add_slave'`

**Comment by hamed169** [comment]
What's wrong with my code??
syntax or argument of function or else???

**Comment by oaubert** [comment]
Please give the output of
```
import vlc
print(vlc.libvlc_get_version())
```

These methods are available only from  libvlc >= 3.0.
