### ISSUE TITLE
Import error on MacOS

### ISSUE THREAD

**Issue by joejacobs** [oaubert/python-vlc#37]
Importing libvlc doesn't work on MacOS. When I try to import VLC (using VLC 3.0 RC9) I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/miniconda/envs/blah/lib/python3.6/site-packages/vlc.py", line 198, in <module>
    dll, plugin_path  = find_lib()
  File "/Users/user/miniconda/envs/blah/lib/python3.6/site-packages/vlc.py", line 183, in find_lib
    dll = ctypes.CDLL(p)
  File "/Users/user/miniconda/envs/blah/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib, 6): Library not loaded: @rpath/libvlccore.dylib
  Referenced from: /Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib
  Reason: image not found
```

It looks like `libvlccore.dylib` needs to be imported first before importing `libvlc.dylib`.

**Comment by oaubert** [comment]
I do not have a Mac at hand to test this, but I would tend to say that this dynamic linker issue should be reported to upstream VLC. I used to solve such issues with install_name_tool some years ago.
Maybe @MrJean1 (who develops on Mac) can give some hints?

**Comment by mrJean1** [comment]
Where can I find VLC 3.0 RC9?  What is environment variable `[DY]LD_LIBRARY_PATH` set to?

There is no problem with VLC 2.2.8 and `python-vlc/generated/3.0/vlc.py` using Python 2.7.14 and 3.6.4 on macOS 10.13.3 High Sierra.

Btw, if VLC 3+ does load multiple `*.dylib`'s, perhaps `[DY]LD_LIBRARY_PATH` should be set, e.g. to the directory where `libvlc.dlib` is found?

**Comment by mrJean1** [comment]
Sorry, I just found [VLC 3.0 RC9](http://nightlies.videolan.org/build/macosx-intel/).

**Comment by oaubert** [comment]
Great work Jean. Could you submit a patch with this modification (so that authorship is preserved)?

**Comment by mrJean1** [comment]
Will do.  But why is this an suddenly an issue?  Does it only happen with the macOS version of VLC?

/Jean

**Comment by oaubert** [comment]
Something must have changed in the macosx build chain. The extras/package/macosx directory of VLC has had lots of changes these last months.  I would even expect that https://github.com/videolan/vlc/commit/f6e51b027f3bd458af1626f90b05de36ad6621ef (and the following one removing build-package.sh) look like the ones that could have introduced the issue.

**Comment by mrJean1** [comment]
Submitted patch for the header.py file.

/Jean

**Comment by oaubert** [comment]
I don't see the patch. Where did you submit it?

**Comment by mrJean1** [comment]
Not sure what happened.  Redid the patch and it should be there now as mrJean1-patch-1.

/Jean

**Comment by smilemcm** [comment]
in my case, there is no C library in my system..
so I installed the vlc application through apple store.
in my case application directory is  "/Applications/VLC 2.app/Contents/MacOS/lib"
so i open vlc.py file in python lib,
I change the directory name like below 

`    elif sys.platform.startswith('darwin'):
        # FIXME: should find a means to configure path
        #d = '/Applications/VLC.app/Contents/MacOS/'.        <- origin directory name
        d = '/Applications/VLC 2.app/Contents/MacOS/'.        <- my system directory
        c = d + 'lib/libvlccore.dylib'
        p = d + 'lib/libvlc.dylib'
        if os.path.exists(p) and os.path.exists(c):
            # pre-load libvlccore VLC 2.2.8+
            ctypes.CDLL(c)
            dll = ctypes.CDLL(p)`

**Comment by AccelQuasarDragon** [comment]
Just a quick note because this thread keeps popping up on my google searches:

If you are packaging with pyinstaller for Mac, VLC.app MUST be installed in the applications folder for it to work smoothly.

If VLC is not in the applications folder (for example you want your .app to work regardless if the user has previously installed VLC), you must add `libvlccore.dylib` and `libvlc.dylib` manually in the spec file, and modify vlc.py to search in the _MEIPASS folder:

adding dylibs in the .spec file
```
a.binaries + [
        ("libvlc.dylib", "/Users/KivySchool/CODING/BasicPyVLC/VLC.app/Contents/MacOS/lib/libvlc.dylib", "BINARY"),
        ("libvlccore.dylib", "/Users/KivySchool/CODING/BasicPyVLC/VLC.app/Contents/MacOS/lib/libvlccore.dylib", "BINARY")
        ],
```

vlc.py changed to look in `sys._MEIPASS` folder
```
elif sys.platform.startswith('darwin'):
    d = sys._MEIPASS
    c = os.path.join(d, "libvlccore.dylib")
    p = os.path.join(d, "libvlc.dylib")
    print("paths exists and loaded?", c, p, os.path.exists(p), os.path.exists(c))
    if os.path.exists(p) and os.path.exists(c):
        # pre-load libvlccore VLC 2.2.8+
        ctypes.CDLL(c)
        dll = ctypes.CDLL(p)
        for p in ('modules', 'plugins'):
            p = os.path.join(d, p)
            if os.path.isdir(p):
                plugin_path = p
                print("pluginpath", plugin_path, os.path.exists(plugin_path))
                break
```
