### ISSUE TITLE
python vlc can't read webm and 3gp stream

### ISSUE THREAD

**Issue by GuillaumeMilan** [oaubert/python-vlc#40]
First sorry for all the **** i did by closing and reopening the issue. 

I was wondering if it was on purpose or a bug if python-vlc can't read 3gp and webm file on stream while vlc can. 

Indeed python-vlc read perfctly mp4 files but when you try to read webm files or gp3 the read crash and have for logs:
```
[0x2aa45b8] main input error: open of `https://r3---sn-n4g-jqb6.googlevideo.com/videoplayback?itag=17&key=yt6&mime=video%2F3gpp&gir=yes&clen=161008&signature=9DCBA41482947F4FFA589AFDE01E2C0D69B7FE65.C6F4BC9E47C741EFFE6553E504FF77A73F1CA15D&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&source=youtube&expire=1519593014&ipbits=0&lmt=1478874226847504&initcwndbps=598750&ip=77.136.42.117&ms=au%2Crdu&mv=m&mt=1519571288&requiressl=yes&dur=17.043&id=o-ACZWg2uwmoF7F9GVoXWAabQ_Dk478Q_4jg-9TOJi66Ke&mn=sn-n4g-jqb6%2Csn-25glenes&pl=23&mm=31%2C29&fvip=5&ei=1tGSWvnXJsbiW5CYuaAL&c=WEB&ratebypass=yes' failed
[0x2aa45b8] main input error: Your input can't be opened
[0x2aa45b8] main input error: VLC is unable to open the MRL 'https://r3---sn-n4g-jqb6.googlevideo.com/videoplayback?itag=17&key=yt6&mime=video%2F3gpp&gir=yes&clen=161008&signature=9DCBA41482947F4FFA589AFDE01E2C0D69B7FE65.C6F4BC9E47C741EFFE6553E504FF77A73F1CA15D&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&source=youtube&expire=1519593014&ipbits=0&lmt=1478874226847504&initcwndbps=598750&ip=77.136.42.117&ms=au%2Crdu&mv=m&mt=1519571288&requiressl=yes&dur=17.043&id=o-ACZWg2uwmoF7F9GVoXWAabQ_Dk478Q_4jg-9TOJi66Ke&mn=sn-n4g-jqb6%2Csn-25glenes&pl=23&mm=31%2C29&fvip=5&ei=1tGSWvnXJsbiW5CYuaAL&c=WEB&ratebypass=yes'. Check the log for details.
```
I have 2 questions:
1) where do you save your log? (i didn't find them in /var/log)
2) is it an issue, an unimplemented feature or a miss usage of mine.

Regards 
GuillaumeMilan

**Comment by GuillaumeMilan** [comment]
I think i miss understood the problem I was facing.
This is a problem of file extension (certificate don't disallow you to play). 
Vlc don't read 3gp files

**Comment by mrJean1** [comment]
How are you opening the `input` with Python-VLC?

**Comment by GuillaumeMilan** [comment]
In my class i got this code to initialize the player:
```
#define the instance of vlc
        self.__instance = vlc.Instance()
#define the player of the class 
        self.__player = self.__instance.media_player_new()
```
And then i only do 
```
self.__player.set_mrl(url)
self.__player.play()
```

**Comment by mrJean1** [comment]
How is the `url` argument to `.set_mrl(url)` quoted or encoded?  Like [urllib.quote](https://docs.python.org/2/library/urllib.html#urllib.quote) or [urllib.quote_plus](https://docs.python.org/2/library/urllib.html#urllib.quote_plus)?

**Comment by GuillaumeMilan** [comment]
I get this url via pafy. 
So it looks like that:
`https://r6---sn-n4g-jqbl.googlevideo.com/videoplayback?signature=484506D8B3D9687A1EB9ACF0012A2B4CC708DF8D.CDB503BA35A81C3281CF5AD165F52DF013108D29&c=WEB&lmt=1464405648624888&key=yt6&itag=17&beids=%5B9466594%5D&fvip=4&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&clen=31692&source=youtube&dur=3.111&initcwndbps=516250&ei=RN6SWr6oDJekVoC1l5gB&expire=1519596196&mv=m&mn=sn-n4g-jqbl%2Csn-25glen7l&mm=31%2C29&pl=23&mime=video%2F3gpp&id=o-ADN_nt4TAfVKqyg0TyX50TEkLiL3Eq1AOUMYnmhtx8dq&ipbits=0&requiressl=yes&ip=77.136.42.117&gir=yes&mt=1519574512&ms=au%2Crdu&ratebypass=yes`

**Comment by mrJean1** [comment]
Alright.  In that case, try this (assuming you're using Python 2):

```
import urllib
...
self.__player.set_mrl(urllib.unquote(url))
...
```

**Comment by GuillaumeMilan** [comment]
Thanks, 
Unfortunately I use Python 3. But I assume it exist an equivalent in Python 3. 
I will find it and try it. 
Thanks

**Comment by mrJean1** [comment]
No problem.  The `unquote` function is in an other module in Python 3.

**Comment by GuillaumeMilan** [comment]
Still go the error.

**Comment by mrJean1** [comment]
There is no such error with `urllib.unquote("https://...")` in Python 2.7.14 on macOS.  Atay tuned, will try Python 3, next.

**Comment by mrJean1** [comment]
Works fine with `urllib.parse.unquote("https://...mv=m")` in Python 3.6.4 on macOS too, no error: the trombone sound is playing, same sound as in the browser and in the VLC app.

**Comment by GuillaumeMilan** [comment]
How does the player get the url to play in your code. Which player do I launch with this new way to set the mrl?

**Comment by mrJean1** [comment]
Look at the correction I just made in the previous post.  That is just copied from the example in Python-VLC `generated/vlc.py`.

**Comment by GuillaumeMilan** [comment]
I do not use the github version of python-vlc but the pip3 one. 
My vlc own no include files as expected by the github project. Should I reinstall vlc in devel mode?

**Comment by mrJean1** [comment]
No sure, I doubt the development vs pip3 version will make a difference.  At this point, I expect the problem to be in the url or something else before VLC gets it.

**Comment by GuillaumeMilan** [comment]
Yes but I can't see the `generated/vlc.py` example because i can't make the project... So I can't see the way you got no trouble.

**Comment by mrJean1** [comment]
The `generated/vlc.py` from the development version is the very same `vlc.py` that is in your Python3 `.../lib/python3site-packages` directory.  But feel free to get the development version.

**Comment by mrJean1** [comment]
Tried with the `pip3` version in Python 3.6.4 as follows ... No error, same sound.

```
% python3
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import vlc
>>> i = vlc.Instance()
>>> p = i.media_player_new()
>>> u = "https://r6---sn-n4g-jqbl.googlevideo.com/....ms=au%2Crdu&ratebypass=yes"
>>> import urllib.parse
>>> u = urllib.parse.unquote(u)
>>> p.set_mrl(u)
<vlc.Media object at 0x1032280b8>
>>> p.play()
0
```

**Comment by GuillaumeMilan** [comment]
Ok I just did the exact same thing than you and still get the error. I don't understand. I think the error is awkward and may depend of my system. 
``` 
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```
It's not a big issue for me so don't get to much in it ;)
Thanks for the time you took.

**Comment by mrJean1** [comment]
Sorry, that I can't help any further with that issue.  Do other videos play, like `python3 vlc.py <video_filename>` from the command line?
