### ISSUE TITLE
Access to currently displayed subtitle path

### ISSUE THREAD

**Issue by Neraste** [oaubert/python-vlc#42]
Hi, thanks for this app!

I can explicitly add a subtitle to a media with `media.add_options("sub-file=my_file.ass")`. If `sub-autodetect` is enabled (by default), another subtitle can be displayed instead. It seems there is no way to know which subtitle is currently displayed.

With `player.get_media().tracks_get()`, I can access to the tracks of the media, but the `SubtitleTrack` object only contains `encoding`. Is it possible to access to more information from the track? Ultimately, the path to the subtitle file would be great.

**Comment by oaubert** [comment]
It looks (from reading the doc, not actually testing it) like you need player.get_spu(): https://www.olivieraubert.net/vlc/python-ctypes/doc/vlc-module.html#libvlc_video_get_spu
