### ISSUE TITLE
`This object event manager doesn't know about 'Unknown Event' events` when trying to attach MediaListEndReached callback to MediaListPlayer

### ISSUE THREAD

**Issue by devxpy** [oaubert/python-vlc#43]
```
libvlc_get_version()
b'2.2.6 Umbrella'
```

```
>>> import vlc

>>> player = vlc.MediaListPlayer()

>>> e = vlc.EventType.MediaListEndReached

>>> def f(*args, **kwargs):
...     print("END REACH", args, kwargs)

>>> player.event_manager().event_attach(e, f)
This object event manager doesn't know about 'Unknown Event' events
```

**Comment by mrJean1** [comment]
Just to confirm (with VLC 2.2.8 on macOS), the EventType.Media**List**EndReached is not known somehow, not only for a MediaListPlayer and also not for a MediaPlayer instance.  In addition, an EventType.Media**Player**EndReached is also unknown for a Media**List**Player but that event **is** known for a MediaPlayer instance.

**Comment by oaubert** [comment]
You are using a version of the module that was generated for vlc 3.0, hence has the vlc.EventType.MediaListEndReached defined. If you use the module generated for 2.2 ( https://github.com/oaubert/python-vlc/tree/master/generated/2.2 ) then the symbol will not be defined, so you know you are not expected to use it with this version.

**Comment by devxpy** [comment]
[Technical Support]
I have installed it using `snap install vlc` but i cant seem to link it.

I tried `export PYTHON_VLC_LIB_PATH=/snap/bin/vlc` but that doesn't work

using Ubuntu 17.10

**Comment by mrJean1** [comment]
Here's 3.0.0:
```
>>> import vlc300 as vlc
>>> vlc.__version__
'3.0.0101'
>>> vlc.__libvlc_version__
'3.0.0'
>>> p = vlc.MediaListPlayer()
>>> e = vlc.EventType.MediaListEndReached
>>> def f(*args, **kwargs):
...     print("END REACH", args, kwargs)
... 
>>> p.event_manager().event_attach(e, f)
This object event manager doesn't know about 'Unknown Event' events-1
```

Like 2.2.8, that EventType is defined, but it's unknown when used.  Shouldn't it be undefined if it can't be used?

**Comment by devxpy** [comment]
@mrJean1 are you using windows?

**Comment by mrJean1** [comment]
No, I'm on macOS.

**Comment by devxpy** [comment]
There is no vlc 3 in the apt repository. 

The only way to install without actually building sources is through snap, and that doesn't install to the system directly.

**Comment by mrJean1** [comment]
Sorry, I’m not familiar with snap, Ubuntu, etc.  Can’t you get the VLC 3.0 libs from [here](https://www.videolan.org/vlc/releases/3.0.0.html)?

**Comment by devxpy** [comment]
I wish it was that easy.
```
Ask your favorite packager for VLC 3.0!
```
