### ISSUE TITLE
No Access to Pitch / Roll/ Yaw / FOV

### ISSUE THREAD

**Issue by JosephRHendry** [oaubert/python-vlc#50]
After creating a video viewpoint object with:
`v = vlc.libvlc_video_new_viewpoint()`

To control a 360 video, I should be able to set the pitch, roll, yaw and FOV for the view. According to one of the mods for libvlc, I should just be able to set the variable directly rather than through a separate function.

Looking through the VLC code (specifically /include/vlc_viewpoint.h) it seems like a Viewpoint should initialize all those variables to zero, but I don't see those variables, and if I manually create them, (such as `v.yaw = 5`) it no affect on the libvlc_video_update_viewpoint() function.

Considering the implementation of the python wrapper, is there any reason to expect that these variables would be accessible in a different way?

**Comment by JosephRHendry** [comment]
A colleague of mine found a work around. By altering the class definition of VideoViewpoint(_Cstruct) in vlc.py and adding an extra underscore after "_fields" it is possible to create a viewpoint (`v = VideoViewpoint()`) and then to set the variables as expected (`v.yaw=5`). This then updates the viewpoint as expected. But it doesn't seem to work with a viewpoint created in the expected way (ie `v = vlc.libvlc_video_new_viewpoint()`)

**Comment by oaubert** [comment]
Thanks for the report. This issue (_fields_ definition) is now fixed. Note that libvlc_video_new_viewpoint() returns a pointer to a VideoViewpoint struct, so its content must be addressed through `v.contents.yaw`
