### ISSUE TITLE
Function libvlc_video_set_adjust_float produces no changes

### ISSUE THREAD

**Issue by JosephRHendry** [oaubert/python-vlc#51]
Using commands such as:

``vlc.libvlc_video_set_adjust_float(p, 2, 0)``

Do not alter the brightness, nor have I been able to alter any of the other VideoAdjustOption variables.

I've tried several permutations of the command, for instance:

``vlc.libvlc_video_set_adjust_int(p, 0, True)``
``vlc.libvlc_video_set_adjust_float(p, 2, 200)``

The first command (of which I tried variations) was an attempt to set "Enable" to true, but it doesn't seem to make a difference.

I've also tried

``vlc.libvlc_video_set_adjust_float(p, 'Brightness', 0)``

To no effect.

Is there an error in my syntax or perhaps a bug in the code?

**Comment by mrJean1** [comment]
Olivier,

AFAICT, there’s no Python definition for the second parameter of these functions, option, an enum libvlc_video_adjust_option_t <https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__video.html#ga1093996bbcbb93f0d0a49636917f09c4> anywhere in vlc.py, for enum values like libvlc_adjust_Enable, libvlc_adjust_Contrast, libvlc_adjust_Brightness, libvlc_adjust_Hue, libvlc_adjust_Saturation and libvlc_adjust_Gamma.

Yet another question is how/where to find the type of each option to use the proper libvlc_video_set_adjust_{int,float,…} function?

/Jean

**Comment by mrJean1** [comment]
Sorry, there is a vlc.py _Enum called VideoAdjustOption which list the values I mentioned below.

The confusion is that the documention for the option parameter refers to the libvlc_video_adjust_option_t and not  VideoAdjustOption.

Perhaps we should add something like

__doc__.replace("libvlc_video_adjust_option_t”, “VideoAdjustOption")

in one of the Python generators.

/Jean
 

> Olivier,
> 
> AFAICT, there’s no Python definition for the second parameter of these functions, option, an enum libvlc_video_adjust_option_t <https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__video.html#ga1093996bbcbb93f0d0a49636917f09c4> anywhere in vlc.py, for enum values like libvlc_adjust_Enable, libvlc_adjust_Contrast, libvlc_adjust_Brightness, libvlc_adjust_Hue, libvlc_adjust_Saturation and libvlc_adjust_Gamma.
> 
> Yet another question is how/where to find the type of each option to use the proper libvlc_video_set_adjust_{int,float,…} function?
> 
> /Jean
> 
>

**Comment by JosephRHendry** [comment]
Thanks for the responses mrJean1. Just to provide a little more info, I've tried utilizing VideoAdjustOption somewhat. For example:

``f = vlc.VideoAdjustOption()``

Which, when I print 'f' it returns "VideoAdjustOption.Enable"

After declaring f, I've also tried:
``f.Brightness = 1``

But since libvlc_video_set_adjust_float() requires three parameters, setting the value of Brightness seems pointless.

I also tried:
``vlc.libvlc_video_set_adjust_float(p, f.Brightness, 1)``

But to no avail.

**Comment by JosephRHendry** [comment]
Tried, but with no luck.

**Comment by mrJean1** [comment]
FWIW,

Using the cocoalvlc.py example player on macOS, I tried changing the brightness of a running video with

  player.video_set_adjust_float(vlc.VideoAdjustOption.Brightness, 0.8)

and then retrieving the value using

  player.video_get_adjust_float(vlc.VideoAdjustOption.Brightness)

The returned value matches to set value.  However, the brightness of the video does not seem to change at all.

Also, using

  player.video_set_adjust_bool(vlc.VideoAdjustOption.Enable, True)

does not make any difference.

/Jean

**Comment by oaubert** [comment]
To identify whether the problem lies in the bindings or in the libvlc code itself, could you try to execute the set_adjust function in a minimal C example?  Save the [sample.txt](https://github.com/oaubert/python-vlc/files/2060356/sample.txt) file (as sample.c), and replace the `libvlc_media_set_meta`  line with an appropriate call to `libvlc_video_set_adjust_float`.

**Comment by mrJean1** [comment]
Olivier,

I’m unable to compile and link the sample program, some libraries are missing on the iMac I’m using.  

However, there is no question that the issue is in libvlc, IMO.  After a .video_set_adjust_float call to set a different value, the next .video_get_adjust_float returns that same value.  Isn’t that evidence that libvlc does get and return the value?

Also, I tried with different values for .Brightness, like 0.5..1.0 and 50..100.  The value changes, but the brightness doesn’t.

All this is on macOS 10.13.4 (High Sierra) with VLC 3.0.1.

/Jean

**Comment by JosephRHendry** [comment]
I was also unable to get the sample to compile, but I used the code from: https://wiki.videolan.org/LibVLC_Tutorial/ and got that to run. However, I don't seem to be able to change the brightness.

Here's the command I used:
``libvlc_video_set_adjust_float(mp, 2, 1.0);

It executes without issue, but there's no change to brightness. My C is pretty rusty though.

**Comment by mrJean1** [comment]
The brightness of a (running or stopped) video does change with

  player.video_set_adjust_float(vlc.VideoAdjustOption.Brightness, b)

However, this only works and after first calling**

  player.video_set_adjust_int(vlc.VideoAdjustOption.Enable, 1)

and if 0 <= b <= 2.0**.

To retrieve the brightnes value use

  player.video_get_adjust_float(vlc.VideoAdjustOption.Brightness)

/Jean

**) Based on file VLCMediaPlayer.m <https://github.com/strukturag/VLCKit/blob/master/Sources/VLCMediaPlayer.m> lines 509-520 in the (obsolete?) VLCKit <https://github.com/strukturag/VLCKit/tree/master/Sources>.  ObjC code to get/set Contrast, Gamma, Hue and Saturation is nearby.

PS) Isn't there some VLC documentation to explain this, the types of the VideoAdjustOptions and the range of valid -Option values?

**Comment by JosephRHendry** [comment]
Awesome! Thanks Jean!

**Comment by mrJean1** [comment]
Keep in mind, the type of all VideoAdjustOptions is float, except .Hue and .Enable.  Those are int.

Also the range for each Option is different.  The values shown in that VLCMediaPlayer.m file may no longer be valid, to be verified.

/Jean

**Comment by oaubert** [comment]
I think the best way to cope with this would be to imitate VLCKit and add wrapper methods for each parameter (brightness, hue...) that automatically set .Enable to True when invoked and convert values to float/int automatically. It is only a matter of adding get_*/set_* methods to `generator/templates/override.py`

**Comment by mrJean1** [comment]
That’s one way to go and each setter needs to check the valid range of the option.  Or keep python-vlc as-is but provide some documentation and examples for the VideoAdjustOption-s.

More testing (with VLC 3.0.1 on macOS) shows that only setting AdjustOption-s .Enable and .Brightness work.  All other AdjustOption-s have no visual effect, it seems.

Also, it is not necessary to set .Enable to 1 before every other AdjustOption call.  One .Enable call is sufficient and after that all subsequent AdjustOption.Brightness calls work as expected.  But none of the other AdjustOption-s seem to work, both with and without a .Enable call per setting.

/Jean

**Comment by JosephRHendry** [comment]
I'm getting Saturation to work as well, haven't tried any of the others yet, but I just replaced "Brightness" with "Saturation" and kept the same value ranges.

**Comment by JosephRHendry** [comment]
Have now tested the rest of the floats and they are all working on my system (Brightness, Gamma, Contrast, Saturation). I'm using Ubuntu 18.04, VLC v3.0.2

**Comment by mrJean1** [comment]
Indeed, the value of the option changes after setting it, but only "Brightness" has a noticable, visual change in my case.  Attached is a screen shot (VCL 3.0.1 on macOS).
![cocovlcvideoadjustoptionbrightness](https://user-images.githubusercontent.com/22154337/40855196-d939c478-65a1-11e8-9f30-a7938f658633.jpg)

**Comment by JosephRHendry** [comment]
Can confirm that the other options are producing visible changes. Here's saturation set to 2.0

![screenshot from 2018-06-01 10-52-44_2](https://user-images.githubusercontent.com/38083167/40855752-484ad004-658a-11e8-8846-f6b538bbcf4a.png)

Vs. Unaltered:
![screenshot from 2018-06-01 10-57-09_2](https://user-images.githubusercontent.com/38083167/40855856-a96de31c-658a-11e8-9ea1-ea587a654916.png)

**Comment by mrJean1** [comment]
Great!  Same on macOS now, all options do have visual effect.  There was a bug in my code, _mea culpa_.

**Comment by mrJean1** [comment]
The VLC documentation on [VideoAdjustOption](https://wiki.videolan.org/Documentation:Modules/adjust/) is pretty close.  But like [VideoMarqueeOption](https://wiki.videolan.org/Documentation:Modules/marq/) there no mention that .Enable had to be set to 1 first.

**Comment by michmich76** [comment]
with "python.exe -m pip install python-vlc"

Hello.
Can you help me ?
I just want to play a video and change the hue.

but my code doesn't work!
the video is played.
but without changing the Hue

my code :

####################################
import vlc
Instance = vlc.Instance()

player = Instance.media_player_new()

Media = Instance.media_new_path('myvideo.mp4')
player.set_media(Media)

player.video_set_adjust_int (vlc.VideoAdjustOption.Enable, 1)
player.video_set_adjust_float (vlc.VideoAdjustOption.Enable, 1)

player.video_set_adjust_float (vlc.VideoAdjustOption.Brightness, 2)
player.video_set_adjust_float (vlc.VideoAdjustOption.Hue, 350)

player.play()
####################################

help me
thanks

**Comment by mrJean1** [comment]
Referring to the VLC [docs](https://Wiki.VideoLan.org/Documentation:Modules/adjust) and [cocoavlc.py](https://github.com/oaubert/python-vlc/blob/master/examples/cocoavlc.py), options Enable, Brightness and Hue are all `int`.  Try this ...

```
player.video_set_adjust_int (vlc.VideoAdjustOption.Enable, 1)
player.video_set_adjust_int (vlc.VideoAdjustOption.Brightness, 2)
player.video_set_adjust_int (vlc.VideoAdjustOption.Hue, 350)

```

**Comment by michmich76** [comment]
hello mrJean1,

thank you for your reply.
but, no, it doesn't work.

the video launches, but no modification of Brightness, or Hue!

thanks

**Comment by mrJean1** [comment]
Correction.  All adjust options are `float`, except Enable.  Also, try setting the options before playing the video.

**Comment by michmich76** [comment]
hello,

No still does not work!
and I read the doc but ...?

with the following code I have the video but without hue or Brightness change!

but the console does display the correct values !

>>> 
130
10.0
>>> 


my code
------------------------------------------------

import vlc
Instance = vlc.Instance()
player = Instance.media_player_new()

player.video_set_adjust_int(vlc.VideoAdjustOption.Enable, 1)

player.video_set_adjust_int(vlc.VideoAdjustOption.Hue, 130)
player.video_set_adjust_float(vlc.VideoAdjustOption.Brightness, 10)

Media = Instance.media_new_path('myvideo.mp4')
player.set_media(Media)


ahue=player.video_get_adjust_int (vlc.VideoAdjustOption.Hue)
bbrig=player.video_get_adjust_float(vlc.VideoAdjustOption.Brightness)

player.play()

print (ahue)
print (bbrig)
----------------------------------------------------------------
thanks

**Comment by mrJean1** [comment]
The max Brightness is 2 (not 10) and use video_set_adjust_float for Hue (not _int).

**Comment by michmich76** [comment]
yes I know.
I've already done !
but don't work!
and the console gives :

0         !!!!!!!!!!!!!!!!!!!   when that should be 130  !!!!!
2.0


my code :


...
player.video_set_adjust_int(vlc.VideoAdjustOption.Enable, 1)
player.video_set_adjust_float(vlc.VideoAdjustOption.Hue, 130)
player.video_set_adjust_float(vlc.VideoAdjustOption.Brightness, 2)

ahue=player.video_get_adjust_int (vlc.VideoAdjustOption.Hue)
bbrig=player.video_get_adjust_float(vlc.VideoAdjustOption.Brightness)


print (ahue)
print (bbrig)

**Comment by mrJean1** [comment]
Use video_get_adjust_**float** for Hue.

**Comment by mrJean1** [comment]
Btw, what is the version of `vlc.py` and `libvlc`?

**Comment by michmich76** [comment]
hello

oK... I Use video_get_adjust_float for Hue

my code :
player.video_set_adjust_float(vlc.VideoAdjustOption.Hue, 130)
ahue=player.video_get_adjust_float (vlc.VideoAdjustOption.Hue)
print (ahue)  
and the console  return :      0  !!! it is strange !

I'm a beginner
how to know "what is the version of vlc.py and libvlc" ?

thanks

sorry I french

**Comment by mrJean1** [comment]
In a console or terminal window type

`python vlc.py -v`

**Comment by michmich76** [comment]
print (vlc.__version__)
retun : 3.0.7110

**Comment by mrJean1** [comment]
OK, what is the version of `libvlc` or `VLC`?

**Comment by michmich76** [comment]
VLC 2.0.3 Twoflower
how to know "what is the version of libvlc" ? sorry

**Comment by mrJean1** [comment]
OK.  Upgrade your VLC to the [latest version 3.0.8](https://www.videolan.org/vlc/index.html), especially since your `vlc.py` is 3.07110.  Then, use this:

```
import vlc
instance = vlc.Instance()
player = instance.media_player_new()
media = instance.media_new_path('myvideo.mp4')
player.set_media(media)

player.video_set_adjust_int(vlc.VideoAdjustOption.Enable, 1)
player.video_set_adjust_float(vlc.VideoAdjustOption.Hue, 130)
player.video_set_adjust_float(vlc.VideoAdjustOption.Brightness, 2)

print('hue', player.video_get_adjust_float(vlc.VideoAdjustOption.Hue))
print(bright', player.video_get_adjust_float(vlc.VideoAdjustOption.Brightness))

player.play()
```

**Comment by michmich76** [comment]
YES !!!!

it works

Thanks you...

**Comment by mrJean1** [comment]
Très bien!

**Comment by michmich76** [comment]
Merci encore...

**Comment by Rickgrendel** [comment]
So is this also possible while playing a video? Because it's possible to do that in the vlc application. If I try to apply the brightness after the video starts playing with:

`
media_player.video_set_adjust_int(vlc.VideoAdjustOption.Enable, 1)
media_player.video_set_adjust_int(vlc.VideoAdjustOption.Brightness, 0)
`

but if I try this I get:

`
[000001ae81527330] main filter error: Failed to create video converter
[000001ae81524310] chain filter error: Too high level of recursion (3)
`

I don't know if this is related or expected but some help would be appreciated.

Rick

**Comment by mrJean1** [comment]
Not sure about that `main filter error`, but use `video_set_adjust_float(vlc.VideoAdjustOption.Brightness, 0)`.  All `VideoAdjustOption.`s required `float` except option `Enable`.
