### ISSUE TITLE
how can I get current real-time buffer size in vlc streaming buffer through python-vlc?

### ISSUE THREAD

**Issue by maozezhong** [oaubert/python-vlc#61]
I want to get the current real-time buffer size while vlc streaming video, How can I get it through python-vlc. real-time buffer size means like, a video is stream from one server to one client, vlc get it and stored it in a buffer pool, and vlc decode the data in the pool so as to show the video currently, what I want is the size or time of video data in the pool during the streaming.

**Comment by maozezhong** [comment]
@mrJean1 , hello, thank you for your reply. Is it possible to get buffer size through `input-bitrate` and `demux_bitrate` ? Like in my opinion, input bitrate means the vidieo data stream to the current pool, and demux bitrate is the data get out from the current pool , So I can simply get buffer size through this two parameter, am I right?

**Comment by mrJean1** [comment]
Possibly, using one of [these cache](https://superuser.com/questions/683520/how-to-increase-vlc-ram-buffer-for-offline-files) sizes.   But you may have to _set_ the cache size from Python since there doesn't seem to be a way to _get_ any of these sizes.

**Comment by mrJean1** [comment]
It turns out there are command line options to _set_ the caching values:

```
% /Applications/VLC.app/.../VLC --help --advanced
    ...
    Advanced:
      --file-caching <integer [0 .. 60000]>    File caching (ms)
      --live-caching <integer [0 .. 60000]>    Live capture caching (ms)
      --disc-caching <integer [0 .. 60000]>    Disc caching (ms)
      --network-caching <integer [0 .. 60000]>    Network caching (ms)
    ...
```

From Python, you could set these as follows, _untested however_:

```
i = Instance(["--file-caching=2000 --network-caching=3000"])
p = i.media_player_new()
...
```

**Comment by maozezhong** [comment]
@mrJean1 Thanks a lot! It seems to set the caching values means to set the total size of the buffer pool, like, when I set the file-caching=2000, it means the upper limit of buffer pools is 2000ms, in another word, the max time of video the buffer pool can store is 2000ms. what I want to get is the real-time buffer size when streaming the video data, because the pool is not always full, so 2000ms may not be the value I want, am I right? So, any other adivce? correct me if I am wrong~

**Comment by maozezhong** [comment]
OK, Thanks a lot anyway!

**Comment by mrJean1** [comment]
Just to explain, the buffer size is _probably not just_ the bitrate times the caching time.

**Comment by maozezhong** [comment]
Ok, So `(read_bytes -demux_read_bytes ) / input_bitrate` may not be the caching time? what is the buffer size exactly?

**Comment by mrJean1** [comment]
Like my previous comment, this may not be that simple either.  Just don’t know and don’t have an authoritative answer, sorry.

**Comment by maozezhong** [comment]
ok, thank you for your patient reply~

**Comment by mrJean1** [comment]
As an experiment, the latest `examples/cocoavlc.py` computes **input-caching** as `(read_bytes - demux_read_bytes) / (input_bitrate * 1000)` in seconds and `(read_bytes - demux_read_bytes)` in bytes.

Typical values are around `30 s` and `70 KiB` for sample videos, see [cocoavlc-snapshotX-TableWindow.pdf](https://github.com/oaubert/python-vlc/files/2268717/cocoavlc-snapshotX-TableWindow.pdf).  Are those valid figures?

**Comment by floris-vos** [comment]
this is closed - I suppose it means that this is just impossible?
I tried with MediaStats, but couldn't get any kind of reasonable buffer or cache info.

**Comment by mrJean1** [comment]
The `MediaStats` struct hasn't changed in VLC since the examples shown above.  And that's all `vlc.py` can provide.
