### ISSUE TITLE
apply video-filter to running vlc.Instance() 

### ISSUE THREAD

**Issue by k0a1a** [oaubert/python-vlc#63]
By the analogy to 'Effects and filters' panel in the VLC player is there a way to apply a video-filter to an already running vlc.Instance?

In particular, I'm interested in Adjust video filter, I'm reading that an API for it is already in libvlc

**Comment by mrJean1** [comment]
Here's one example, listing the available video filters with `python-vlc 3.0.2012`, `VLC 3.0.3` on macOS 10.13.6:

```
p = vlc.MediaPlayer()
m = p.set_mrl(<video_file_name>)
i = p.get_instance()
for f in sorted(i.video_filter_list_get()):
    print(f)
...
```

The forthcoming [cocoavlc.py](http://GitHub.com/oaubert/python-vlc/tree/master/examples) and [PyCocoa](http://PyPI.org/project/PyCocoa) releases 18.8.14 will show the video filters as a panel, see attached.

![cocoavlcvideofilters](https://user-images.githubusercontent.com/22154337/44241604-fc994380-a192-11e8-9d51-befbc9be06b2.jpg)

Similarly for audio filters.

**Comment by k0a1a** [comment]
Off-topic, plus I couldn't care less about macOS-specific implementations.

**Comment by mrJean1** [comment]
All right.  _I hesitate to mention this_ ... the example [cocoavlc.py](https://github.com/oaubert/python-vlc/tree/master/examples) uses all 6 Adjust video options (plus some of the idiosyncrasies thereof) and ... nearly all is _not macOS-specific!_

**Comment by oaubert** [comment]
AFAIK, you have to specify the filters when instanciating the libvlc Instance. There was a time when it was possible to dynamically specify some filters by adding options to Media objects, but this feature has been removed after an architectural rework, as noted in https://www.olivieraubert.net/vlc/python-ctypes/doc/vlc-module.html#libvlc_media_add_option
