### ISSUE TITLE
Play VLC without GUI

### ISSUE THREAD

**Issue by marcosboggia** [oaubert/python-vlc#64]
Hi, i would like to know if it is possible to run for eg. vlc.MediaPlayer() with no interface. I tried using:
```python
player = vlc.MediaPlayer(sdp_path, ":Idummy",":network-caching=1", ":sout-mux-caching=<>")
```
... with no success. Thanks!

**Comment by oaubert** [comment]
I would say

``player = vlc.MediaPlayer("--vout=dummy", sdp_path)``

**Comment by marcosboggia** [comment]
I tried it, first i had to change params order because in my case the first parameter is the path. Then it keeps me throwing the same errors: 
```
gl vout display error: parent window not available
gles2 vout display error: parent window not available
xcb vout display error: window not available
```
Do you happen to know if there is a workaround for this? Thanks!

**Comment by oaubert** [comment]
I typed too fast: you should first create a ``vlc.Instance`` (where you can specify command line parameters) then instanciate a mediaplayer. That would be:

``i = vlc.Instance("--vout=dummy")
p = i.media_player_new()
p.set_mrl(sdp_path)``

**Comment by marcosboggia** [comment]
Thanks it worked!

**Comment by lucasbittencourt02** [comment]
Hi,

I´m trying create a python script using vlc without gui, however i receiving the same error above.

`import vlc
import time

player=vlc.MediaPlayer('rtsp://XXXX:YYYY@XXX.YYY.ZZZ/h264/ch1/main/av_stream')
player.play()

while 1:
    time.sleep(10)
    player.video_take_snapshot(0, '.snapshot.tmp.jpg', 0, 0)

`
Created new TCP socket 14 for connection
Created new TCP socket 10 for connection
[00007fdf68009ac0] gl vout display error: parent window not available
[00007fdf68009ac0] gles2 vout display error: parent window not available
[00007fdf68009ac0] xcb vout display error: window not available
[00007fdf68009ac0] fb vout display error: cannot get terminal mode (Inappropriate ioctl for device)
Segmentation fault (core dumped)
``

**Comment by oaubert** [comment]
This is very OS-dependent. What is your OS ? I would guess you are on MacOS X, from the tried modules. In this case, have a look at the `cocoavlc.py` example in the examples directory.

**Comment by lucasbittencourt02** [comment]
I´m using ubuntu 18.04

**Comment by mbps54** [comment]
what's news? Is it possible to get screenshot from video without gui?

**Comment by mrJean1** [comment]
Did you try the `MediaPlayer.video_get_snapshot` method?

**Comment by mbps54** [comment]
No, I'm trying this way:

import vlc
import time
opt = "--aout=adummy"
instance = vlc.Instance(opt)
player = instance.media_player_new()
media = instance.media_new('rtsp://192.168.1.244:554/profile1')
player.set_media(media)
player.play()
time.sleep(1)
player.video_take_snapshot(0, 'image_snapshot_1.txt', 400, 300)

**Comment by mrJean1** [comment]
The extension `.txt` may be a problem.  It must be `.png`, `.jpg`, `.jpeg` or `.tiff`.

**Comment by mbps54** [comment]
Oh, txt is just one of example what I have tried. If I execute this script on a Ubuntu with GUI, everything is OK, but in case of Debian with CLI only, it does not work...

**Comment by mrJean1** [comment]
Try `player.video_take_snapshot(0, 'image_snapshot_1`**.png, 0, 0)** and --**.jpg, 0, 0)** and --**.tiff, 0, 0)**.

**Comment by iburakov** [comment]
To improve on [@oaubert's solution](https://github.com/oaubert/python-vlc/issues/64#issuecomment-418640413), `media_player_new` seems to be able to accept the media uri as the first argument:
```python
i = vlc.Instance("--vout=vdummy")
p = i.media_player_new(sdp_path)
```

**Comment by tyeth** [comment]
Try `export DISPLAY=:0 ` then it allows vlc to play with no display setup.
