### ISSUE TITLE
Take snapshot without writing to disk

### ISSUE THREAD

**Issue by marcosboggia** [oaubert/python-vlc#66]
Hi, currently I am playing a stream and grabbing a snapshot with the following code:
```python
i = vlc.Instance("--vout=dummy --network-caching=200 --sout-mux-caching=<>")
p = i.media_player_new()
p.set_mrl(sdp_path)
p.play()
while True:
    p.video_take_snapshot(0, '/home/ubuntu/stream.png', 0, 0)
    # ...code that uses stream.png...
    time.sleep(0.1) # 10 FPS
```
I would like to know if it is possible to avoid writing to disk and grab the frame and save it to a variable. I tried using named pipes but `video_take_snapshot()` exits with error.
Thanks!

**Comment by oaubert** [comment]
Such an API existed in previous control API (in past years), but did not make it into the libvlc API. So I guess named pipes are the only option now. This is not python-vlc specific, but libvlc-specific, you could ask for this feature on forum.videolan.org.

**Comment by oaubert** [comment]
Note that this feature has been implemented in latest development tree of VLC. The API is wrapped in the python bindings, but not yet tested.

**Comment by maylad31** [comment]
hi can you let me know where is this feature

**Comment by oaubert** [comment]
It is the `libvlc_media_thumbnail_request_by_pos` and `libvlc_media_thumbnail_request_by_time` functions, that have been wrapped as `thumbnail_request_by_pos` and `thumbnail_request_by_time` methods of the `Media` class. See http://www.olivieraubert.net/vlc/python-ctypes/doc/vlc.Media-class.html#thumbnail_request_by_time

As mentioned, it has not yet been tested (by myself at least) so do not be suprised if there are some issues. Please report them (or success).

**Comment by maylad31** [comment]
Thank you very much for the quick response i will try to understand the function and use it and also report if i find any issue.

**Comment by maylad31** [comment]
hello can you please help me again? I get a message "more than 5 seconds of late video..." while running rtsp stream. Is there any way I could solve it? If i increase network caching the problem is solved but then i get a delay.Thanks again.
