### ISSUE TITLE
audio_output_device_get() returns NameError: no function

### ISSUE THREAD

**Issue by MarcusKulik** [oaubert/python-vlc#7]
```python
import vlc
vlci = vlc.Instance('pathtoplugins')
vlcp = vlci.media_player_new()

vlcp.audio_output_device_get()
```
 gives error:
```python
NameError: no function 'libvlc_audio_output_device_get'
```
and for the life of me without this working I can't figure out how to get the device id to use in
```python
vlcp.audio_output_device_set(None, 'device id')
```
Win 10/ latest VLC/PyCharm 5.0.1

**Comment by oaubert** [comment]
What is precisely your libvlc version ? The function you are looking for is available for libvlc 3.0 and higher (as mentioned in the documentation : https://olivieraubert.net/vlc/python-ctypes/doc/vlc-module.html#libvlc_audio_output_device_get ). To know you libvlc version, you can execute

  import vlc
  print vlc.libvlc_get_version()

**Comment by MarcusKulik** [comment]
Ah I'm on version 2.2.1. I had just done a fresh install of VLC so I assumed it would have the most up to date version.

Sorry but I can't really find clear instructions on updating my lbvlc version without compiling all of VLC which honestly is beyond my understanding.

**Comment by oaubert** [comment]
libvlc 3.0.0 is the version in the current dev tree. If you want to
test it before its release, without compiling it yourself, you may
check http://nightlies.videolan.org/

**Comment by MarcusKulik** [comment]
Sorry about the late reply. Got it all working now, thanks!
