### ISSUE TITLE
Missing MediaPlayer() after clean pip3 installation? 

### ISSUE THREAD

**Issue by Kosakk** [oaubert/python-vlc#73]
Executing a script which was previously running fine, threw me a missing vlc module error. Trying to better understand what that was about, I managed to get a more detailed python error. After dealing with that also, I tried to execute my script once more, and for a second it seemed like it was running okay, until I received an AttributeError: module 'vlc' has no attribute 'MediaPlayer'. Only I had `player=vlc.MediaPlayer('somefile')` in my script, and that was running fine before. After I ran out of ideas, I pip3 uninstall(ed) vlc module and pip3 install(ed) vlc again. 

The MediaPlayer() method seems to be still missing.

**Comment by oaubert** [comment]
For this kind of report, please copy/paste the exact mentioned errors, with their stack trace. It looks like you have some corrupted version of vlc installed, since the MediaPlayer class is always defined in it. Start from a fresh directory to make sure you do not have any leftover file (like .pyc)
