### ISSUE TITLE
How to pass command-line options?

### ISSUE THREAD

**Issue by BlackLight** [oaubert/python-vlc#75]
Is there a way to pass command-line options to the VLC instance or the MediaPlayer?

[The official documentation](https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__core.html#ga915aa5778053d7b52ff9f6ba6e2f7764) mentions an `*argv` passed to `libvlc_new()`, but nowhere is documented which parameters are supported.

I've tried with different combinations for `--fullscreen`:

```python
import vlc

f = 'media.mp3'

# 1
p = vlc.MediaPlayer(f, '--fullscreen')
# 2
p = vlc.MediaPlayer(f, 'fullscreen')
# 3
p = vlc.MediaPlayer(f, '-f')
# 4
inst = vlc.Instance('--fullscreen')
p = vlc.MediaPlayer(f)
# 5
inst = vlc.Instance('fullscreen')
p = vlc.MediaPlayer(f)
# 6
inst = vlc.Instance('-f')
p = vlc.MediaPlayer(f)

p.play()
```

None of these could open the media in fullscreen. What am I doing wrong?

**Comment by oaubert** [comment]
The official documentation for the bindings wrapper is at https://www.olivieraubert.net/vlc/python-ctypes/
Your question has actually 2 answers: 
- you can provide parameters as strings when creating the `vlc.Instance` instance, e.g. `inst = vlc.Instance('--verbose 2')` 
- the --fullscreen will not be honoured by the vlc Instance. You should use the API method `vlc.libvlc_set_fullscreen(p, True)` (where p is a vlc.MediaPlayer).
