### ISSUE TITLE
vlc.MediaPlayer.set_media() crashes whole process

### ISSUE THREAD

**Issue by mvforell** [oaubert/python-vlc#77]
I'm developing a media player using `python-vlc` and it works like a charm - except for one thing:

I'm using `Qt for Python` and have defined my own classes. There is a method called `__action_next` to handle skipping to the next file to play, which is also attached via a wrapper function (which ignores the event parameter and just calls `__action_next`) to the MediaPlayerEndReached event.

When this function is called by clicking the skip button, everything works as expected. But when the end of the currently playing file is reached and the `MediaPlayerEndReached` event triggers, the UI stops responding and stopping the program via the cli (CTRL-C) does not work either. There is no cli output indicating what exactly the problem may be.

Through debugging I found out that the function call which crashes is probably:
`self._vlc_mediaplayer.set_media(self._vlc_medium)`

Before this line, `self._vlc_medium` is updated and parsed, `self._vlc_mediaplayer` is set up at program start.

**Comment by oaubert** [comment]
libvlc is not reentrant, i.e. you cannot call a libvlc function directly from an event handler, it must be called from the main thread. See https://forum.videolan.org/viewtopic.php?t=130714#p440116

**Comment by mvforell** [comment]
Ah, I didn't know that. Thanks a lot for the fast reply and for this project in general! :)
