### ISSUE TITLE
media.get_duration() extremely unreliable

### ISSUE THREAD

**Issue by wootiown** [oaubert/python-vlc#78]
media.get_duration and the equivalent alias for the MediaPlayer object both cannot actually provide a length until the track is played. Additionally, rarely a track returns -1 for the length despite it working fine previously.

**Comment by oaubert** [comment]
It is not unreliable: it requires that the media is parsed before it gets any metadata (duration, track listing, other metadata...). This is documented in libvlc for tracks_get https://www.olivieraubert.net/vlc/python-ctypes/doc/vlc.Media-class.html#tracks_get but I agree that the same note should be duplicated where appropriate. I did commit a fix for libvlc, it will be updated in the next bindings release.

**Comment by wootiown** [comment]
I appreciate the update to documentation. After parsing a media object using the a URL for audio, I'm still getting -1 returned consistently for media.get_duration. After playing the track briefly then pausing, I'm able to get the duration MOST of the time but sometimes it randomly returns -1 and I'm unable to find a cause.
