### ISSUE TITLE
How to set --x11-display arg in python-vlc?

### ISSUE THREAD

**Issue by neosarchizo** [oaubert/python-vlc#79]
Hi.

I made a python vlc program by python-vlc. It works very well. 
And I want to run it on reboot by crontab.
I also added `DISPLAY=:0` in crontab.
But it isn't executed on reboot.

I found [a related answer](https://stackoverflow.com/questions/9636268/play-a-video-with-vlc-in-x11-from-remote-terminal?answertab=votes#tab-top).

I want to set `--x11-display` arg of cvlc in python-vlc.
But I can't find same method in python-vlc.

Thanks.

**Comment by oaubert** [comment]
You should pass the parameter when instanciating a `vlc.Instance` object, which will then be used to get a media player:

```
i = vlc.Instance('--x11-display', ':0')
p = i.media_player_new()
p.set_mrl('/path/to/movie.mp4')
p.play()
```
