### ISSUE TITLE
Missing libgcc_s_seh-1.dll

### ISSUE THREAD

**Issue by postelrich** [oaubert/python-vlc#8]
With Win7, running `pip install python-vlc` and then running the following in ipython:

    import vlc
    inst = vlc.Instance()

Causes a System Error to popup:

    python.exe - System Error

    The program can't start because libgcc_s_seh-1.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by oaubert** [comment]
I do not have a windows machine, but according to extras/package/win32/package.mak in the vlc source code, this file should be bundled in the vlc directory. What is the path you installed vlc in ?

**Comment by postelrich** [comment]
I installed it to C:/Program Files.  I had tried searching in the VideoLan directory but didn't find it.  Is it only a 32-bit package?

**Comment by postelrich** [comment]
I fixed the error by downloading the dll and adding it to my conda environment's Library/bin folder.
