### ISSUE TITLE
Premature State.Ended on youtube songs

### ISSUE THREAD

**Issue by Str8cucked** [oaubert/python-vlc#84]
Some songs, although rare, are given State.Ended prematurely when playing through python. I found this issue when I would check song states for my youtube music player. I had the program check if the song is playing or paused so the loop can continue and end when the song ends. Recently however some songs would skip and not give an error and after some testing I found this was the reason.

**Comment by oaubert** [comment]
There could be some issue due to stalled buffering. You should report this to forum.videolan.org since it concerns libvlc, and not the bindings themselves.
