### ISSUE TITLE
macosx vout display error: No drawable-nsobject nor vout_window_t found, passing over

### ISSUE THREAD

**Issue by lingzhiyanna** [oaubert/python-vlc#91]
[00007ff6d6a17d10] macosx vout display error: No drawable-nsobject nor vout_window_t found, passing over.
[00007ff6d6156af0] main video output error: video output creation failed
[00007ff6dc18dc10] main decoder error: failed to create video output
[h264 @ 0x7ff6d6045800] get_buffer() failed
[h264 @ 0x7ff6d6045800] thread_get_buffer() failed
[h264 @ 0x7ff6d6045800] decode_slice_header error
[h264 @ 0x7ff6d6045800] no frame!

**Comment by mrJean1** [comment]
On macOS, try running the example [python-vlc/examples/cocoavlc.py](https://github.com/oaubert/python-vlc/blob/master/examples/cocoavlc.py) as `python cocoavlc.py <video_file_name>`.

**Comment by lingzhiyanna** [comment]
[00007fb69feb0190] videotoolbox decoder: Using Video Toolbox to decode 'h264'
[00007fb69feb0190] videotoolbox decoder: vt cvpx chroma: 420v
Segmentation fault: 11

**Comment by lingzhiyanna** [comment]
python-vlc/examples/tkvlc.py  

 if platform.system() == "Linux":  # for Linux using the X Server
                self.player.set_xwindow(self.GetHandle())
            elif platform.system() == "Windows":  # for Windows
                self.player.set_hwnd(self.GetHandle())
            elif platform.system() == "Darwin":  # for MacOS 
                self.player.set_nsobject(self.GetHandle()) 

[00007fb69feb0190] videotoolbox decoder: Using Video Toolbox to decode 'h264'
[00007fb69feb0190] videotoolbox decoder: vt cvpx chroma: 420v
Segmentation fault: 11

**Comment by mrJean1** [comment]
Please ryn `python vlc.py -v` and/or `python3 vlc.py -v`and show the results.

**Comment by lingzhiyanna** [comment]
YongqingdeMacBook-Pro:~ yongqingwang$ python vlc.py -v
/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'vlc.py': [Errno 2] No such file or directory

**Comment by lingzhiyanna** [comment]
YongqingdeMacBook-Pro:~ yongqingwang$ pip install python-vlc
Requirement already satisfied: python-vlc in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (3.0.6109)
YongqingdeMacBook-Pro:~ yongqingwang$ python vlc.py -v
/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'vlc.py': [Errno 2] No such file or directory
YongqingdeMacBook-Pro:~ yongqingwang$

**Comment by mrJean1** [comment]
Try  `python -m vlc -v` since vlc.py is installed.

**Comment by lingzhiyanna** [comment]
YongqingdeMacBook-Pro:~ yongqingwang$ python -m vlc -v
vlc.py: 3.0.6109 (Sun Mar 31 20:14:16 2019 3.0.6)
LibVLC version: 3.0.7.1 Vetinari (0x3000701)
LibVLC compiler: clang: warning: argument unused during compilation: '-mmacosx-version-min=10.7' [-Wunused-command-line-argument]
Plugin path: /Applications/VLC.app/Contents/MacOS/plugins
Python: 3.7.3 (64bit) macOS 10.14.5

**Comment by mrJean1** [comment]
Thank you.   That all looks OK.   The segmentation fault is due `tkvlc.py` not passing the correct object to `player.set_nsobject()` for recent macOS versions.

Try to install `PyCocoa` with `pip install pycocoa`.   Also, get a copy of the `cocoavlc.py` from [GitHub](https://github.com/oaubert/python-vlc/blob/master/examples/cocoavlc.py) and save that in your current directory.   Then, run `python cocoavlc.py` and select a video from the dialog window.  Or run `python cocoavlc.py <video_file_name>`.

**Comment by lingzhiyanna** [comment]
Thank you.

**Comment by mrJean1** [comment]
In `tkvlc.py`, the handle obtained from `Tk.ttk.Frame.winfo_id()` and passed to `vlc.media_player.set_nsobject()` is _certainly_ not the correct `NSView` type required by macOS Cocoa.  Testing showed that it also does not seem to be a Cocoa `NSWindow` object from which the `NSView` can be obtained with the `NSWindow.contentView` message.

It will take some time to figure out what `Tk.ttk.Frame.winfo_id()` returns and how to get the `NSView` from there.  Until then, the `tkvlc.py` example is seriously broken on current macOS and probably should issue a message to that effect.

**Comment by mrJean1** [comment]
One more observation.  Using `self.player.set_xwindow(self.GetHandle())` on macOS instead of `self.player.set_nsobject(self.GetHandle())` plays the audio but not the video and does not segfault.  This is with the _original_ `tkvlc.py` dated 23-09-2015, `vlc.py 3.0.6109`, `VLC 3.0.6  Vetinari (0x3000600)` and  `tkinter.TkVersion 8.6` bundled with Python 3.7.4 (64 bit) on macOS 10.13.6.

**Comment by mrJean1** [comment]
Here is an attempt to make `tkvlc.py` work on recent macOS versions.  In method `Player.OnOpen` changing the following lines:

```
            if platform.system() == 'Windows':
                self.player.set_hwnd(self.GetHandle())
            else:
                self.player.set_xwindow(self.GetHandle()) # this line messes up windows
```
to:

```
            h = self.GetHandle()
            if platform.system() == 'Windows':
                self.player.set_hwnd(h)
            elif platform.system() == 'Darwin':  # for MacOS
                from ctypes import c_void_p, cdll, util
                libtk = cdll.LoadLibrary(util.find_library('libtk'))
                if libtk:  # get the window's NSView attribute
                    # getNSView = libtk.TkMacOSXDrawableView  # XXX not found?
                    getNSView = libtk.TkMacOSXGetRootControl
                    getNSView.restype = c_void_p
                    getNSView.argtypes = c_void_p,
                    self.player.set_nsobject(getNSView(h))
                else:
                    self.player.set_xwindow(h)  # audio, no video
            else:
                self.player.set_xwindow(h) # this line messes up windows
```
plays the video and audio in the main, top-level window, see the attached screen shots.

That is not quite correct, but at least there is a way to get the `NSView`.  Using function `libtk.TkMacOSXDrawableView` may solve that, see `tk8.6.9` source file `macosx/tkMacOSXSubwindows.c`.

However, for some reason the symbol `TkMacOSXDrawableView` can't be found in the `libtk` library (although that symbol does show up in `nm /Library/Frameworks/Python.framework/Versions/3.7/lib/libtk8.6.dylib --s | grep Drawable`).  Or perhaps the Tk window/frame/pane should be constructed differently.

 ![tkvlc py screenshot1](https://user-images.githubusercontent.com/22154337/61837703-f35d3000-ae53-11e9-89c7-ee4d71d80c9f.jpg)
![tkvls py screenshot2](https://user-images.githubusercontent.com/22154337/61837705-f7894d80-ae53-11e9-9597-5d40e8f54c06.jpg)

**Comment by mrJean1** [comment]
Just for the record, example` tkvlc.py` version 20.05.04 works with `Python 3.9.2`, `tkinter/Tk 8.6`, `vlc.py 3.0.11115`, `libvlc/VLC.app 3.0.11` on `macOS 11.2.2 Big Sur (Intel)` in 64-bit ...

![tkvlc+Python3 9 2+vlc py3 0 1115+VLC3 0 11+macOS11 2 2BigSur](https://user-images.githubusercontent.com/22154337/110212860-653c8e80-7e6b-11eb-802b-d8b0a33d7a81.jpg)

**Comment by alycda** [comment]
`tkvlc.py` version 20.05.04 on Python 3.9.2, `tkinter 8.6 N/A`, `vlc.py 3.0.11115`, `libvlc 3.0.11.1` on `macOS 10.15.7 (19H524) Catalina` does not work.

`python3 tkvlc.py` opens a player, selecting an mp4 from File > Open results in:
```
[00007fe063d57ea0] caopengllayer vout display error: No drawable-nsobject found!
[00007fe063d57ea0] macosx vout display error: No drawable-nsobject nor vout_window_t found, passing over.
[00007fe05f8130f0] main video output error: video output creation failed
[00007fe063d4d9b0] main decoder error: failed to create video output
[h264 @ 0x7fe05d070400] get_buffer() failed
[h264 @ 0x7fe05d070400] thread_get_buffer() failed
[h264 @ 0x7fe05d070400] decode_slice_header error
[h264 @ 0x7fe05d070400] no frame!
[00007fe061fbac30] caopengllayer vout display error: No drawable-nsobject found!
``` 
`python3 tkvlc.py file.mp4` does not open the file
```
[00007fe061fc9e50] caopengllayer vout display error: No drawable-nsobject found!
[00007fe061fc9e50] macosx vout display error: No drawable-nsobject nor vout_window_t found, passing over.
[00007fe05d81f4f0] main video output error: video output creation failed
[00007fe063d4d9b0] main decoder error: failed to create video output
[h264 @ 0x7fe05d051c00] get_buffer() failed
[h264 @ 0x7fe05d051c00] thread_get_buffer() failed
[h264 @ 0x7fe05d051c00] decode_slice_header error
[h264 @ 0x7fe05d051c00] no frame!
```

cocoavlc.py works

**Comment by mrJean1** [comment]
Please show the output of ...

`python3 vlc.py -v`

**Comment by alycda** [comment]
> python3 vlc.py -v

```
vlc.py: 3.0.11115 (Sun Jan 10 13:06:33 2021 3.0.11)
LibVLC version: 3.0.11.1 Vetinari (0x3000b01)
LibVLC compiler: clang: warning: argument unused during compilation: '-mmacosx-version-min=10.7' [-Wunused-command-line-argument]
Plugin path: /Applications/VLC.app/Contents/MacOS/plugins
Python: 3.9.2 (64bit) macOS 10.15.7
```

> python3 tkvlc.py -v

`tkvlc.py: 20.05.04 (tkinter 8.6 N/A)`

>python3 tkvlc.py file.mp4

<img width="760" alt="Screen Shot 2021-03-17 at 8 29 26 PM" src="https://user-images.githubusercontent.com/1791092/111569226-7afd5e00-875f-11eb-83ef-9d9ea2626c0b.png">

**Comment by mrJean1** [comment]
The problem is the `tkinter` library is not found or loaded by Python 3.9.2 ...

```
python3 tkvlc.py -v
tkvlc.py: 20.05.04 (tkinter 8.6 N/A)
```

That line should be someting like ...

`tkvlc.py: 20.05.04 (tkinter 8.6 /Library/Frameworks/Python.Framework/Version/3.9/lib/libtk8.6.dylib)`

The `tkinter` libtary is included in recent [Python 3 downloads](http://www.Python.org/downloads/mac-osx/) for macOS.

**Comment by alycda** [comment]
I do have tkinter installed, this worked for me: https://solarianprogrammer.com/2018/04/21/python-opencv-show-video-tkinter-window/

**Comment by mrJean1** [comment]
That may be correct, but `tkvlc.py` can not find that `tkinter` library ... because `tkvlc.py` looks for the `tkinter` library included with Python.  Check the `tkvlc.py` source at [line 52](https://github.com/oaubert/python-vlc/blob/master/examples/tkvlc.py#L52).

**Comment by alycda** [comment]
@mrJean1 I'm new to Python, which error was thrown (NameError OSError) to rewrite `'/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9'` to `"N/A"`?

<img width="1440" alt="Screen Shot 2021-03-17 at 9 22 40 PM" src="https://user-images.githubusercontent.com/1791092/111573175-3ecdfb80-8767-11eb-90cf-851a8957ac20.png">

**Comment by mrJean1** [comment]
That is a tricky but it may work.  Instead, try to change line 61 and set `libtk =` to that path name of the `libtk...dylib`.  The lines following 61 are critical.

**Comment by alycda** [comment]
on line 61 libtk IS equal to `/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/libtk8.6.dylib`, but it seems the next line fails: `dlopen(/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/libtk8.6.dylib, 6): image not found`

<img width="1076" alt="Screen Shot 2021-03-18 at 12 29 34 AM" src="https://user-images.githubusercontent.com/1791092/111588610-06d3b200-8781-11eb-989b-5052b164c263.png">

**Comment by mrJean1** [comment]
In that traceback, the line ...

`OSError: dlopen(‘...’)...`

shows that the `libtk8.6.dylib` file does not exist, is not valid or can’t be opened for some reason.  The ‘@‘ character in the path may be another issue, not certain.  Type ...

`ls -al /usr/local/.../libtk8.6.dylib`

in a Terminal window.

**Comment by alycda** [comment]
Ah I see that file does not exist on my system. I installed Python3.9 using homebrew. I re-installed but that file still does not exist for 3.8 nor 3.9

```
$ ls -lah /usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.9/lib
libpython3.9.dylib -> ../Python
pkgconfig
python3.9
```

**Comment by mrJean1** [comment]
Looks like homebrew does not include Tcl/Tk, `libtk... dylib` etc. with Python builds.

Get Python 3.9.2 for macOS 10 from `Python.org` and install that somewhere else or on an other mac.  Also get `tkvlc.py`, `vlc.py` and the `VLC App` on that mac.  Play a video to make sure that it all works.

Type `python3 tkvlc.py -v` and then make a copy of _that_ `libtk8.6.dylib` file and put the in the homebrew version.

**Comment by alycda** [comment]
@mrJean1 Thank you, I already had `tcl-tk` installed via homebrew, so I copied the following files from `/usr/local/Cellar/tcl-tk/8.6.11_1/lib` into `/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib`

- libtcl8.6.dylib
- libtclstub8.6.a
- libtk8.6.dylib
- libtkstub8.6.a

```
/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libtk8.6.dylib
tkvlc.py: 20.05.04 (tkinter 8.6 /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libtk8.6.dylib)
```

now I see the app working as expected, it launches with a video, the video can play/pause/etc.

Thank again

**Comment by mrJean1** [comment]
Glad that `tkvlc.py` works with just those 4 `libtcl`... and `libtk`... files in place.

However, those files are just 4 of 2 dozen Tcl/Tk files and folders bundled with Python builds from `python.org`.  Other `tkinter/Tk` application may or may not work, like Python’s own `IDLE`.
